### ISSUE TITLE
Tooltips clutter page

### ISSUE THREAD

**Issue by openpaul** [ProteinsWebTeam/interpro7-client#102]
Tooltips in search dont disappear if scrolled.

How to reproduce:
On this page: https://www.ebi.ac.uk/interpro/beta/entry/panther/?search=Ribosomal%20protein%20L1&page=3#table
Hover the mouse over the field "family" to make tooltip "family type (as defined by panther)" occur.
Scrolling will then result in multiple tooltips that dont disappear.

![interpro_Screenshot_2019-07-05_09-24-51](https://user-images.githubusercontent.com/3997610/60709245-e2ca3180-9f07-11e9-9b03-8065e78247b0.png)

**Comment by gustavo-salazar** [comment]
I haven't been able to replicate. But we just did a release of the app, could you please check if is still happening on your side.
I tried chrome and firefox in Mac, what is your setup?

**Comment by openpaul** [comment]
its gone now. thakns
