### ISSUE TITLE
Approximate or exact counts?

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-client#107]
https://www.ebi.ac.uk/interpro/beta/proteome/uniprot/entry/sfld/#table

Mouseover on a number in the entry column and  you get 'Approximately X' where X is the number highlighted. But they are not round numbers: are they really exact counts?

**Comment by gustavo-salazar** [comment]
Because of the way elasticsearch deals with the aggregations all the counts should be considered approximates. The smaller the number the higher the confidence. However it is just safer to always say the number are approximations.
