### ISSUE TITLE
Searching for taxa 

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-client#108]
From here:

https://www.ebi.ac.uk/interpro/beta/taxonomy/uniprot/entry/sfld/?search=human#table

I can put 9606 in the box, as well as human, but would expect it to also match, say, "homo s" and show the same species. It works with other 'partial' strings, try for example homos and it picks up "Mychonastes homosphaera (Green alga)", maybe a problem with the space character?

**Comment by gustavo-salazar** [comment]
I think you are right about thinking the whitespace is the culprit.
Our settings in elasticsearch use the edge_ngram tokenizer [(Read more)](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html).

This splits the words so when looking for "homo s" it will be searching for "homo" and "s". Moreover, the minimum size of a token has been chosen to be 2, and therefore it wont find the "s" token. Thats why searching for "homo sa" actually works ([see example](https://www.ebi.ac.uk/interpro/beta/taxonomy/uniprot/entry/sfld/?search=homo%20sa#table)).
