### ISSUE TITLE
Show entry fullname and entry type somewhere in protivista component on Protein Summary page

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#116]
The current website only show entry short names in popups on every track. Hsin-Yu has suggested that it's difficult to get an overview of function this way. InterPro 6 shows Entry type and names for matches. We could  show both these items of information in the protvista component for integrated entries. Not sure about unintegrated entries.

![Screenshot 2019-07-25 at 11 22 04](https://user-images.githubusercontent.com/892047/61867158-758a3a80-aece-11e9-8672-30d641c1b402.png)
![Screenshot 2019-07-25 at 11 21 55](https://user-images.githubusercontent.com/892047/61867159-758a3a80-aece-11e9-8113-12b2cb0f6df7.png)

**Comment by gustavo-salazar** [comment]
Deployed. Example: https://www.ebi.ac.uk/interpro/beta/protein/unreviewed/A0A016T7T4/
