### ISSUE TITLE
Deleted or nonexistent entries load forever

### ISSUE THREAD

**Issue by mattjeffryes** [ProteinsWebTeam/interpro7-client#12]
If you visit the page for a deleted family (eg [IPR000002](https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR000002/)) or a valid but unused accession (eg [IPR9999999](https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR9999999/)) the load indicator runs indefinitely instead of giving you a 404 (or even better, a 410 error for deleted entries).

**Comment by aurel-l** [comment]
Fixed in [fb8d1da](https://github.com/ProteinsWebTeam/interpro7-client/commit/fb8d1da5849373f3f7835afffcf78ff43e2cb5e5) and deployed now.
Now it doesn't display the loading component forever.
It now handles a 410 response, but the API doesn't support it (yet?)
