### ISSUE TITLE
python3 download script failure

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-client#120]
Script fails because of a conversion/decoding error. Fix could use one of:

json.loads(res.read().decode())
json.loads(codecs.decode(res.read()))

I'm also getting duplicate, but differently annotated, entries using the scripts vs via the web. For IPR003609/bacteria I get these fasta entries

>A0A023XWN2|ipr003609|26...76|Uncharacterized protein
>A0A023XWN2|ipr003609|109...160|Uncharacterized protein

With the direct download from the web we get just one:

>A0A023XWN2|unreviewed|Uncharacterized protein|taxID:476282

**Comment by potter-s** [comment]
Note this is py3!

**Comment by CodeGit** [comment]
The script is outputting a new line for each location/fragment matching the protein. ipr003609 matches two locations on A0A023XWN2 so we get two lines in the output of the script. The script doesn't give coordinates so you just get one line reporting the match. I might update the comments in the script to inform users that they will get one line per fragment match.
