### ISSUE TITLE
"Key species" in taxonomy tab does not work

### ISSUE THREAD

**Issue by happy-lorna** [ProteinsWebTeam/interpro7-client#122]
using IPR026017 as an example - I can see the set of key species matches in I6 but in I7 it says "There is no data associated with this accession".

**Comment by gustavo-salazar** [comment]
I just checked and i can see the key species in there: https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR026017/taxonomy/uniprot/#table

Am I missing something here? do you have other example of it?

**Comment by happy-lorna** [comment]
No, my apologies - when I was going through the exercises I didn't notice the "Show Key Species" option. But it is there.
