### ISSUE TITLE
Domain architecture information

### ISSUE THREAD

**Issue by happy-lorna** [ProteinsWebTeam/interpro7-client#125]
Using IPR023897 as an example, when I look at the matching proteins I see the domain architecture of those proteins. However, when I hover over the domain found in the protiens I do not see the information about the domain in the pop-up - I just see the information about the family entry I am looking at.

**Comment by CodeGit** [comment]
Domain architectures have changed quite significantly in the InterPro7 dataset. Architectures are now derived from Pfam domains to prevent overlapping entries. One of the consequences has been that InterPro families no longer have domain architectures. We should definitely document this in the site FAQ or somewhere that users be informed.

**Comment by CodeGit** [comment]
![Screenshot 2019-08-02 at 14 36 11](https://user-images.githubusercontent.com/892047/62374022-f088cc00-b532-11e9-88b7-12230297469c.png)
![Screenshot 2019-08-02 at 14 14 03](https://user-images.githubusercontent.com/892047/62374032-f41c5300-b532-11e9-85f8-06e459f7554e.png)
![Screenshot 2019-08-02 at 14 13 52](https://user-images.githubusercontent.com/892047/62374037-f67ead00-b532-11e9-9b06-f55a0d243ae0.png)
