### ISSUE TITLE
Truncated protein sequence

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-client#127]
https://www.ebi.ac.uk/interpro/beta/protein/UniProt/O95342/

On the sequence tab, only the first line of sequence is displayed. The rest appears to be hidden; if you hit either of the search buttons it uses the full sequence.

**Comment by gustavo-salazar** [comment]
Oh wow, this seems to be a Firefox/ie/edge issue.
When I tried it work on chrome and safari works ok.
I'll investigate.
