### ISSUE TITLE
searching proteomes

### ISSUE THREAD

**Issue by gsn7** [ProteinsWebTeam/interpro7-client#135]
if i search UP000005640. shouldn't i be given a direct link, so that I can go to the proteome UP000005640 overview page as opposed to getting a list of matches for the proteome. 

https://www.ebi.ac.uk/interpro/beta/search/text/UP000005640/

of course this is a case where i would prefer I rather be directly taken to the proteome overview page without having to make the one extra click.

**Comment by gustavo-salazar** [comment]
Seems to me that's an issue in the ebi search index.
@matthiasblum check the query we are executing: https://www.ebi.ac.uk/ebisearch/ws/rest/interpro7?query=UP000005640&format=json&fields=UNIPROT,PDB,PROTEOME,source_database&start=0&size=2
I was expecting to get something for the `PROTEOME` key but the response is an empty array.
Can you please have a look into it?

**Comment by matthiasblum** [comment]
The cross-reference ID to use is `PROTEOMES` (note the plural).
