### ISSUE TITLE
Coverage information on subPages

### ISSUE THREAD

**Issue by aurel-l** [ProteinsWebTeam/interpro7-client#138]
I was thinking it might be useful to see the coverage information of some subPages.

_page type A, subPage type B_: See coverage of B in A
meaning, how much of B is present in/is matched by A.

The case I was interested in was _structure page, protein subPage_.
For example: [proteins in 3oe0](https://www.ebi.ac.uk/interpro/beta/structure/PDB/3oe0/protein/UniProt/#table) where it could display 90% for P61073 and 98% for P00720
In this case it's actually already visible (not the exact value though) in the domain architecture column.
An other easy one would be _entry page, protein subPage_: showing how much of the protein is covered by an entry (for example, [A0A023W6J8 in IPR001165](https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR001165/protein/UniProt/#table) should be about 83 or 84% I think)

But I'm not sure if that could be generalised, or even if it would make sense in some cases. We could have for example the % of an entry (or its signatures) matched by a chain (_structure page, entry subPage_), or by a protein (_protein page, entry subPage_).

Also, that could probably be provided by the API directly.

**Comment by aurel-l** [comment]
If it's in the API that might be useful forwards as a filtering/sorting field (whenever that ends up being added, if ever).
Also, on the "easy cases" that could be used instead of the domain architecture view on narrow screens and/or low-end devices.

**Comment by gustavo-salazar** [comment]
I have tagged this issue as stalled. We discussed this a couple of times, but never agreed on a way to implemented or if it was worth the effort to develop it. So i'm going to close it for now.
