### ISSUE TITLE
Have a "download button" in the protein and taxonomy page in an Entry. 

### ISSUE THREAD

**Issue by EBI-Hsinyu** [ProteinsWebTeam/interpro7-client#15]
For instance in this page, http://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR020422/protein/UniProt/#table, it would be nice to have a button to download all protein FASTA files.

**Comment by 4ndr01d3** [comment]
Implemented as one of the export options of the table. reusing the same concept of download jobs in the taxonomy subpage. TO be on the beta website in the next re-deploy
