### ISSUE TITLE
Show text instead of taxIDs in taxonomy tree breadrumb

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#150]
Suggestion from Rob. Makes a lot of sense, most people don't know taxids but will know names.
![Screenshot 2019-09-23 at 13 24 04](https://user-images.githubusercontent.com/892047/65425475-f6e64680-de05-11e9-968b-f92e9194f470.png)

**Comment by gustavo-salazar** [comment]
That will grow a lot if we use the tax name for the lineage, especially for deep nodes.
I would actually prefer to remove the lineage thanto put the names.
?

**Comment by CodeGit** [comment]
I agree that the names can be quite long and a breacrumb showing all of 
them would look very odd. Perhaps we can replace the breadcrumb with a 
dropdown allowing selection of previous nodes in the lineage?

Escherichia coli
Escherichia
Enterobacteriaceae
Enterobacterales
Gammaproteobacteria
Proteobacteria
Bacteria
cellular organism
