### ISSUE TITLE
Interproscan is run without --goterms and --pathways options

### ISSUE THREAD

**Issue by gsn7** [ProteinsWebTeam/interpro7-client#161]
the interproscan command should include --goterms and --pathways options so that the go terms and the pathways annotations are included in the TSV and other output formats. 

related to this the old site had the protein Id at the top of the results page:
https://www.ebi.ac.uk/interpro/legacy/sequencesearch/iprscan5-S20191004-101824-0027-68748242-p2m
and now that info has disappeared
https://www.ebi.ac.uk/interpro/result/InterProScan/iprscan5-R20191004-094825-0062-96648025-p2m/

**Comment by gustavo-salazar** [comment]
Fixed in commit 0b3e3b905cf31fe77cda503d53d519579e505f6d
Now under code review

**Comment by gustavo-salazar** [comment]
Fix deployed in live
