### ISSUE TITLE
interproscan sequence search input validation etc

### ISSUE THREAD

**Issue by gsn7** [ProteinsWebTeam/interpro7-client#162]
if i search using this sequence
MAKVEQVLSLEPQHELKFRGPFTDVVTTNLKLGNPTDRNVCFKVKTTAPRRYCVRPNSGIIDAGASINVSVMLQPFDYDPNEKSKHKFMVQSMFAPTDTSDMEAVWKEAKPEDLMDSKLRCVFELPAENDKPHDVEINKIISTTASKTETPIVSKSLSSSLDDTEVKKVMEECKRLQGEVQRLREENKQFKEEDGLRMRKTVQSNSPISALAPTGKEEGLSTRLLALVVLFFIVGVIIGKIAL*

ideally this should never be sent to the web service as it contains characters inteerproscan deems illegal. test it on https://www.ebi.ac.uk/interpro/legacy/sequence-search

currently, interpro7 sends this sequence to the webservice and thereafter it reports that the job has finished but doesnt properly report that the search failed. see https://www.ebi.ac.uk/interpro/result/InterProScan/iprscan5-R20191007-120007-0791-73186263-p1m/

**Comment by gustavo-salazar** [comment]
Fix deployed in live
