### ISSUE TITLE
Entry-Taxonomy tree should use pre-calculated data

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#163]
This might make more sense as a JIRA story but we will probably need to update the taxonomy page to handle a pre-calculated taxonomy tree once API changes have been made.

**Comment by gustavo-salazar** [comment]
PR #181 has been merge into dev and the client using it has been deployed in our dev machine:
Examples:
* http://wp-np3-ab.ebi.ac.uk/interpro/taxonomy/uniprot/entry/InterPro/#tree
* http://wp-np3-ab.ebi.ac.uk/interpro/entry/InterPro/IPR000001/taxonomy/uniprot/#tree

**Comment by gustavo-salazar** [comment]
Feature is now live
