### ISSUE TITLE
Make Domain Architectures clearly based on PFAM

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#168]
The new Domain Architecture strategy is based on pfam entries.
We should make this evident to our users:
* @CodeGit can you write some text to introduce these pages:
  * https://www.ebi.ac.uk/interpro/entry/InterPro/IPR000001/domain_architecture/
  * https://www.ebi.ac.uk/interpro/search/ida/
  * https://www.ebi.ac.uk/interpro/protein/UniProt/A0A000/similar_proteins/#table
* It should be a way to toggle the Label to use between Interpro and pfam entries in all the pages above
* the search autocomple is using InterPro entries... it should be extended to also use Pfam

**Comment by Swaathik** [comment]
Domain architectures are shown based on Pfam entries by default. There is a toggle button to switch to InterPro entries in all the mentioned pages. If a clear explanation is added, it would be complete. 

The autocompletion supports Pfam entries in Search by IDA page.
