### ISSUE TITLE
Relationships-the siblings should not be shown in the entry 

### ISSUE THREAD

**Issue by EBI-Hsinyu** [ProteinsWebTeam/interpro7-client#17]
In http://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR020422/, IPR000242 has been listed as having relationships with IPR020422, because they are siblings. This should be removed to avoid confusion.

**Comment by 4ndr01d3** [comment]
Done. TO be in the beta website, in the next redeploy.
