### ISSUE TITLE
Message when redirecting from legacy to live interpro should be removed/updated

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#172]
We could either dispense with the message entirely or update the text

![Screenshot 2019-10-16 at 11 15 17](https://user-images.githubusercontent.com/892047/66910336-4a634300-f006-11e9-917e-e0d868fe50ff.png)

**Comment by gustavo-salazar** [comment]
This is place were the toast is triggered:
https://github.com/ProteinsWebTeam/interpro7-client/blob/9cf0608ef7f650335ff0066c2de56b90d949bfe1/src/store/enhancer/location-middleware/index.js#L50
Not sure if we should keep the toast and change the message, or remove it.

**Comment by gustavo-salazar** [comment]
There are a couple of other places that include beta/ in links e.g. https://www.ebi.ac.uk/interpro/help/documentation/
We should check all around.

Also the link on the homepage to go to the API is broken.

**Comment by Swaathik** [comment]
I checked the links all around in the website. I fixed few that needed corrections. Perhaps one of us can check them randomly for a final check. 

Regarding the message, I feel we can remove it as it is up and running now. The users will submit a ticket if there are issues.
