### ISSUE TITLE
Better handling of timeout responses

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#177]
When the API's response is a 408 Timeout the website says *"No data available"* which is wrong,becuease it is likely that there is data but elastic took to long to respond.
![Screenshot 2019-10-18 at 10 40 23](https://user-images.githubusercontent.com/46671268/67084080-30f00180-f194-11e9-8f8d-acccd6d6a051.png)

**Comment by CodeGit** [comment]
How about something along the lines of:

The query is still running in the background. Please reload in a short while to see the results.

**Comment by gustavo-salazar** [comment]
Yeah that sounds good... but I think the logic in the client needs to be reviewed to be able to identify a timeout from an actual empty response.

**Comment by gustavo-salazar** [comment]
Related to #69

**Comment by gustavo-salazar** [comment]
Loaddata has been updated so it retries requests that have timed out.
EdgeCase now shows when a time-out happen and includes a timer to inform when it would be checked again.
Changes in the `dev` branch

**Comment by gustavo-salazar** [comment]
Included in Tag [1.2.0](https://github.com/ProteinsWebTeam/interpro7-client/tree/1.2.0)
