### ISSUE TITLE
PF13912 not visible in match conservation for S6E5K8 on Firefox

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#180]
<img width="1275" alt="Screenshot 2019-10-30 at 09 20 15" src="https://user-images.githubusercontent.com/25660657/67844946-86ae9d00-faf6-11e9-82e8-4c8d6c15caf4.png">

PF13912 (unintegrated) not visible in match conservation track for S6E5K8 on Firefox, works fine in Chrome.

**Comment by Swaathik** [comment]
Thanks for pointing out. The issue #167 is the same and its been fixed in develop. Once it is merged in master, it would be visible

**Comment by Swaathik** [comment]
Its been merged in master and It is working fine when checked.
