### ISSUE TITLE
Need clearer indication on how to view results on "Your InterProScan searches" page

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#185]
Need to be clearer that you need to click on the job id to view the results on "Your InterProScan searches" page

**Comment by Swaathik** [comment]
How about adding a link icon in front of the job ID to make it obvious that it is a link to the results page?
Like https://www.flaticon.com/free-icon/link-button_61353

**Comment by gustavo-salazar** [comment]
The icon is not actually included in the live version

**Comment by gustavo-salazar** [comment]
Closing this as doesn't seem to be a problem anymore.
