### ISSUE TITLE
Remove error message when Entry does not match key species

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#188]
Seen with 

https://www.ebi.ac.uk/interpro/entry/pirsf/PIRSF000068/taxonomy/uniprot/#table

![Screenshot 2019-11-20 at 12 02 55](https://user-images.githubusercontent.com/892047/69237503-c1ec3b00-0b8d-11ea-8fd3-5ee3901a3c0b.png)

**Comment by Swaathik** [comment]
Amessage is shown that there is no key species for this accession. Like in https://wwwdev.ebi.ac.uk/interpro/entry/pirsf/PIRSF000068/taxonomy/uniprot/#table
