### ISSUE TITLE
release notes page - remove/relocate old release notes

### ISSUE THREAD

**Issue by gsn7** [ProteinsWebTeam/interpro7-client#191]
the top part of the release notes header is useless, on my screen it occupies 1/3 of the functional space.
put the old release notes at the bottom of the page, probably on a single line 

![release-notes-edited-dec-2019](https://user-images.githubusercontent.com/13484190/70067763-abf76500-15e6-11ea-95a5-b194e4189fb9.jpg)

**Comment by Swaathik** [comment]
The old release notes are shown with the link. 
![Screenshot 2019-12-19 at 16 45 18](https://user-images.githubusercontent.com/15231894/71191843-1e22a780-227f-11ea-8cd2-a8c6e79f7088.png)
