### ISSUE TITLE
counter not indicating right number on proteins for InterPro entries

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#194]
ex: http://www.ebi.ac.uk/interpro/entry/InterPro/IPR005070/protein/UniProt/?page_size=100&cursor=j9uwk4#table
shows '1 - 88 of 188 proteins' instead of '100-188 of 188 proteins'

**Comment by gustavo-salazar** [comment]
This is a side effect of the way pagination is working on the API... as we don't have page number anymore, so when a user goes directly to a url with a cursor it is not possible to know how many pages are before this point.

The client emulates this behaviour when the the user is paginating , but if the user loads directly the page, it won't know how many entries have been before.
