### ISSUE TITLE
Add ability to copy/search with sequence of entry on a protein page

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#202]
Nidhi from the Uniprot team asked to be able to get the underlying sequence of an entry hit on a protein in the nightingale component. 

Optionally we could add the option to copy, search in interproscan, search in hmmer with this sequence.

**Comment by gustavo-salazar** [comment]
Changes now in live.
The popup of an entry now includes a button on the location, which directs to the sequence tab, pre selecting the region of the entry
https://www.ebi.ac.uk/interpro/protein/unreviewed/A0A000/sequence/#41-181
