### ISSUE TITLE
Deal with interproscan output result errors

### ISSUE THREAD

**Issue by gsn7** [ProteinsWebTeam/interpro7-client#203]
check
https://www.ebi.ac.uk/interpro/result/InterProScan/iprscan5-R20200127-150506-0728-71262513-p1m/

Hi IPS-Team,

This job and others of the same batch are shown as finished but do not show any results.
Can you please tell me what happened?

Edit:
I didn't realize that the ticket is not opened in relation to the job id.
Here are some of the problematic job ids:
iprscan5-R20200127-151838-0489-92065925-p1m
iprscan5-R20200127-152344-0875-85906804-p1m
iprscan5-R20200127-152527-0885-25306359-p2m
iprscan5-R20200127-150506-0728-71262513-p1m

Best,

**Comment by gustavo-salazar** [comment]
Unfortunately the job ids have already expired, so I can't test with them... and also is hard to replicate the error in the wwwpros service.
I emulated the situation in the client and now it should appear in the list like: 

<img width="686" alt="Screenshot 2020-02-05 at 15 37 10" src="https://user-images.githubusercontent.com/46671268/73856521-7c0a4f00-482d-11ea-82ca-86a9c5e85f1e.png">


And if the user goes into the result of that job it will see something like:

<img width="504" alt="Screenshot 2020-02-05 at 15 38 53" src="https://user-images.githubusercontent.com/46671268/73856634-a8be6680-482d-11ea-8d2c-ed2976f60844.png">
