### ISSUE TITLE
Search for Domain Architecture timeout doesn't display any error

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#205]
Users should be informed that the search has failed and why it failed if possible (or the client should auto-reload and indicate the search is ongoing)

![Screenshot 2020-01-28 at 16 07 35](https://user-images.githubusercontent.com/892047/73281765-586d5600-41e8-11ea-8e49-4fd5b2750012.png)

**Comment by gustavo-salazar** [comment]
Changes done and available in `dev`

**Comment by gustavo-salazar** [comment]
Fixed in Tag 1.2.0
