### ISSUE TITLE
Domain search: Add option to search for exact domain architecture matches

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#206]
A user requested to download a particular domain architecture that contained one and and only one domain. At the moment the domain architecture search will return all proteins containing the entry, however the user wants to exclude all other domains. The current search page doesn't support this option.

e.g PF00293

**Comment by gustavo-salazar** [comment]
This is now in the `future` branch. It requires a change in the API that is already in `dev`, whenever we publish that API, we will merge this to `master`

**Comment by gustavo-salazar** [comment]
Deployed in live: https://www.ebi.ac.uk/interpro/search/ida/
