### ISSUE TITLE
Odd interaction between filters on Protein browse

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#21]
In the following example I'd expect to see 391 proteins not 512

![screen shot 2018-09-28 at 10 32 15](https://user-images.githubusercontent.com/892047/46200754-61a39580-c30a-11e8-8234-826c59a2e72f.png)

**Comment by 4ndr01d3** [comment]
the issue is that the filters uniprot an protein size, together with the final list, include the children of the selected taxonomy.
However the taxonomy filter its more strict and only includes proteins annotated directly with it

**Comment by 4ndr01d3** [comment]
Fix in the API. To be deployed in next release
