### ISSUE TITLE
Show a message when a user navigates to a filtered view from the browse taxonomy tree view

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#210]
The taxonomy tree in the entry page allows navigation to a filtered list of proteins, structures and proteomes. 

![Screenshot 2020-02-21 at 12 35 49](https://user-images.githubusercontent.com/892047/75035179-d00c6900-54a6-11ea-90fe-bf57f14aa292.png)

The pages show a message to the user:

![Screenshot 2020-02-21 at 12 36 10](https://user-images.githubusercontent.com/892047/75035246-f7fbcc80-54a6-11ea-970a-14c4a908bcfa.png)

We should add a similar message when using the browse page taxonomy tree component.

**Comment by gustavo-salazar** [comment]
On PR #211 I have added logic so the links in the browse taxonomy go to the corresponding subpage  of the tax id.
This should avoid the need of the message of this issue.

Additionally in the same PR I updated the taxonomy filter in the protein browse: IN cases were the filtered tax id is not one of the predefined options in the filter, it will create the new option.
