### ISSUE TITLE
Minor fixes: Search By Sequence

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#212]
These are some minor issues still pending from the sign-off document:

* ✅ Also, the '<' goes to the bottom of the page when expanding advance options. 
* ✅ Must remember to change link to train-online when it gets updated
* Advanced options: 
  * ✅ add collapsed/expanded icon? 
  * ✅ PROSITE: label inconsistent with reslease notes; 
  * Pfam: wrong caps on mouseover; 
  * PIRSF: is the ref to PSD correct in the mouseover? 
  * SFLD/CDD/Gene3D/others: no mouseover; 
  * prosite profiles: the 'new' in the mouseover arguably doesn't belong here 
  * references to updates should be in release notes, not static content; 
  * most of the mouseovers say 'scans against', which is probably superfluous; 
  * text under 'Applications' could use some editing.

**Comment by gustavo-salazar** [comment]
The issue of the info icon going to the bottom of the page has been solved and is now in the `dev` branch

**Comment by gustavo-salazar** [comment]
The link in the _"train-online"_ icon doesn't need to be changed because the new tutorial uses the same URL

**Comment by gustavo-salazar** [comment]
The info in the tooltip comes directly from the interproscan web service(https://www.ebi.ac.uk/Tools/services/rest/iprscan5//parameterdetails/appl) 

Not sure if this can be changed on an interproscan release or if we would need to contact wwwprod (any idea @gsn7 ??)

@happy-lorna do you mind checking the text in the web service response, to see if there are any other changes to do in there, besides the ones reported in this ticket.

**Comment by gsn7** [comment]
we should first make changes in interproscan and tell wwwprod to use the descriptions in interproscan
the current interproscan descriptions are:
```
`TIGRFAM (15.0) : TIGRFAMs are protein families based on Hidden Markov Models or HMMs
                         SFLD (4) : SFLDs are protein families based on Hidden Markov Models or HMMs
                      Phobius (1.01) : A combined transmembrane topology and signal peptide predictor
        SignalP_GRAM_NEGATIVE (4.1) : SignalP (organism type gram-negative prokaryotes) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for gram-negative prokaryotes.
                  SUPERFAMILY (1.75) : SUPERFAMILY is a database of structural and functional annotation for all proteins and genomes.
                      PANTHER (14.1) : The PANTHER (Protein ANalysis THrough Evolutionary Relationships) Classification System is a unique resource that classifies genes by their functions, using published scientific experimental evidence and evolutionary relationships to predict function even in the absence of direct experimental evidence.
                       Gene3D (4.2.0) : Structural assignment for whole genes and genomes using the CATH domain structure database
                        Hamap (2020_01) : High-quality Automated and Manual Annotation of Microbial Proteomes
              ProSiteProfiles (2019_11) : PROSITE consists of documentation entries describing protein domains, families and functional sites as well as associated patterns and profiles to identify them
                        Coils (2.2.1) : Prediction of Coiled Coil Regions in Proteins
                        SMART (7.1) : SMART allows the identification and analysis of domain architectures based on Hidden Markov Models or HMMs
                          CDD (3.17) : Prediction of CDD domains in Proteins
                       PRINTS (42.0) : A fingerprint is a group of conserved motifs used to characterise a protein family
              ProSitePatterns (2019_11) : PROSITE consists of documentation entries describing protein domains, families and functional sites as well as associated patterns and profiles to identify them
                  SignalP_EUK (4.1) : SignalP (organism type eukaryotes) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for eukaryotes.
                         Pfam (32.0) : A large collection of protein families, each represented by multiple sequence alignments and hidden Markov models (HMMs)
                   MobiDBLite (2.0) : Prediction of disordered domains Regions in Proteins
        SignalP_GRAM_POSITIVE (4.1) : SignalP (organism type gram-positive prokaryotes) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for gram-positive prokaryotes.
                        PIRSF (3.02) : The PIRSF concept is being used as a guiding principle to provide comprehensive and non-overlapping clustering of UniProtKB sequences into a hierarchical order to reflect their evolutionary relationships.
                        TMHMM (2.0c) : Prediction of transmembrane helices in proteins
```

**Comment by gustavo-salazar** [comment]
@happy-lorna do you mind going through these descriptions to check if the text is alright?

**Comment by happy-lorna** [comment]
`TIGRFAM (15.0) : TIGRFAMs are protein families based on hidden Markov models (HMMs).
SFLD (4) : SFLD is a database of protein families based on hidden Markov models (HMMs).
Phobius (1.01) : A combined transmembrane topology and signal peptide predictor.
SignalP_GRAM_NEGATIVE (4.1) : SignalP (gram-negative) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for gram-negative prokaryotes.
SUPERFAMILY (1.75) : SUPERFAMILY is a database of structural and functional annotations for all proteins and genomes.
PANTHER (14.1) : The PANTHER (Protein ANalysis THrough Evolutionary Relationships) Classification System is a unique resource that classifies genes by their functions, using published scientific experimental evidence and evolutionary relationships to predict function even in the absence of direct experimental evidence.
Gene3D (4.2.0) : Structural assignment for whole genes and genomes using the CATH domain structure database.
Hamap (2020_01) : High-quality Automated and Manual Annotation of Microbial Proteomes.
ProSiteProfiles (2019_11) : PROSITE consists of documentation entries describing protein domains, families and functional sites as well as associated patterns and profiles to identify them.
Coils (2.2.1) : Prediction of coiled coil regions in proteins.
SMART (7.1) : SMART allows the identification and analysis of domain architectures based on hidden Markov models (HMMs).
CDD (3.17) : CDD predicts protein domains and families based on a collection of well-annotated multiple sequence alignment models.
PRINTS (42.0) : A compendium of protein fingerprints - a fingerprint is a group of conserved motifs used to characterise a protein family.
ProSitePatterns (2019_11) : PROSITE consists of documentation entries describing protein domains, families and functional sites as well as associated patterns and profiles to identify them.
SignalP_EUK (4.1) : SignalP (eukaryotes) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for eukaryotes.
Pfam (32.0) : A large collection of protein families, each represented by multiple sequence alignments and hidden Markov models (HMMs).
MobiDBLite (2.0) : Prediction of intrinsically disordered regions in proteins.
SignalP_GRAM_POSITIVE (4.1) : SignalP (gram-positive) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for gram-positive prokaryotes.
PIRSF (3.02) : The PIRSF concept is used as a guiding principle to provide comprehensive and non-overlapping clustering of UniProtKB sequences into a hierarchical order to reflect their evolutionary relationships.
TMHMM (2.0c) : Prediction of transmembrane helices in proteins.
`

**Comment by happy-lorna** [comment]
some tiny tweaks... (apologies for the ugly way they format here - I can't sort it)
`TIGRFAM (15.0) : TIGRFAMs are protein families based on hidden Markov models (HMMs).
SFLD (4) : SFLD is a database of protein families based on hidden Markov models (HMMs).
Phobius (1.01) : A combined transmembrane topology and signal peptide predictor.
SignalP_GRAM_NEGATIVE (4.1) : SignalP (gram-negative) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for gram-negative prokaryotes.
SUPERFAMILY (1.75) : SUPERFAMILY is a database of structural and functional annotations for all proteins and genomes.
PANTHER (14.1) : The PANTHER (Protein ANalysis THrough Evolutionary Relationships) Classification System is a unique resource that classifies genes by their functions, using published scientific experimental evidence and evolutionary relationships to predict function even in the absence of direct experimental evidence.
Gene3D (4.2.0) : Structural assignment for whole genes and genomes using the CATH domain structure database.
Hamap (2020_01) : High-quality Automated and Manual Annotation of Microbial Proteomes.
ProSiteProfiles (2019_11) : PROSITE consists of documentation entries describing protein domains, families and functional sites as well as associated patterns and profiles to identify them.
Coils (2.2.1) : Prediction of coiled coil regions in proteins.
SMART (7.1) : SMART allows the identification and analysis of domain architectures based on hidden Markov models (HMMs).
CDD (3.17) : CDD predicts protein domains and families based on a collection of well-annotated multiple sequence alignment models.
PRINTS (42.0) : A compendium of protein fingerprints - a fingerprint is a group of conserved motifs used to characterise a protein family.
ProSitePatterns (2019_11) : PROSITE consists of documentation entries describing protein domains, families and functional sites as well as associated patterns and profiles to identify them.
SignalP_EUK (4.1) : SignalP (eukaryotes) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for eukaryotes.
Pfam (32.0) : A large collection of protein families, each represented by multiple sequence alignments and hidden Markov models (HMMs).
MobiDBLite (2.0) : Prediction of intrinsically disordered regions in proteins.
SignalP_GRAM_POSITIVE (4.1) : SignalP (gram-positive) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for gram-positive prokaryotes.
PIRSF (3.02) : The PIRSF concept is used as a guiding principle to provide comprehensive and non-overlapping clustering of UniProtKB sequences into a hierarchical order to reflect their evolutionary relationships.
TMHMM (2.0c) : Prediction of transmembrane helices in proteins.`

**Comment by gustavo-salazar** [comment]
Editions by @happy-lorna :
```
TIGRFAM (15.0) : TIGRFAMs are protein families based on hidden Markov models (HMMs). 
SFLD (4) : SFLD is a database of protein families based on hidden Markov models (HMMs). 
Phobius (1.01) : A combined transmembrane topology and signal peptide predictor. 
SignalP_GRAM_NEGATIVE (4.1) : SignalP (gram-negative) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for gram-negative prokaryotes. 
SUPERFAMILY (1.75) : SUPERFAMILY is a database of structural and functional annotations for all proteins and genomes. 
PANTHER (14.1) : The PANTHER (Protein ANalysis THrough Evolutionary Relationships) Classification System is a unique resource that classifies genes by their functions, using published scientific experimental evidence and evolutionary relationships to predict function even in the absence of direct experimental evidence. 
Gene3D (4.2.0) : Structural assignment for whole genes and genomes using the CATH domain structure database. 
Hamap (2020_01) : High-quality Automated and Manual Annotation of Microbial Proteomes. 
ProSiteProfiles (2019_11) : PROSITE consists of documentation entries describing protein domains, families and functional sites as well as associated patterns and profiles to identify them. 
Coils (2.2.1) : Prediction of coiled coil regions in proteins. 
SMART (7.1) : SMART allows the identification and analysis of domain architectures based on hidden Markov models (HMMs). 
CDD (3.17) : CDD predicts protein domains and families based on a collection of well-annotated multiple sequence alignment models. 
PRINTS (42.0) : A compendium of protein fingerprints - a fingerprint is a group of conserved motifs used to characterise a protein family. 
ProSitePatterns (2019_11) : PROSITE consists of documentation entries describing protein domains, families and functional sites as well as associated patterns and profiles to identify them. 
SignalP_EUK (4.1) : SignalP (eukaryotes) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for eukaryotes. 
Pfam (32.0) : A large collection of protein families, each represented by multiple sequence alignments and hidden Markov models (HMMs). 
MobiDBLite (2.0) : Prediction of intrinsically disordered regions in proteins. 
SignalP_GRAM_POSITIVE (4.1) : SignalP (gram-positive) predicts the presence and location of signal peptide cleavage sites in amino acid sequences for gram-positive prokaryotes. 
PIRSF (3.02) : The PIRSF concept is used as a guiding principle to provide comprehensive and non-overlapping clustering of UniProtKB sequences into a hierarchical order to reflect their evolutionary relationships. 
TMHMM (2.0c) : Prediction of transmembrane helices in proteins.
```
@gsn7 can you please use this and start the process with wwwprod?

**Comment by gsn7** [comment]
yup, will do

**Comment by happy-lorna** [comment]
The rest of the tweaks to the mouseover contents (I suspect reported by Rob) are all still relevant.

**Comment by gustavo-salazar** [comment]
The rest of the comments should be corrected once this descriptions get propagated to wwwprod interproscan web service.

**Comment by gustavo-salazar** [comment]
Changes are available from the web service, which updates all the tootips
