### ISSUE TITLE
Minor Issues: Domain Architecture Search

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#213]
These are some minor issues still pending from the sign-off document:
✅Improve error message. Indicate if an accession is not valid
* ✅useful to add "constituent domains" before list of IPRs relating to domains contained in architecture... @happy-lorna do you remember what's this?
✅IDA block: somehow show this is for "more info"
✅ Not clear that the '<' would take me to help. Maybe change to '?'
* ✅doesn't appear to be any documentation on IDA

**Comment by happy-lorna** [comment]
I think the "constituent domains" issue was because at one time (possibly just due to page loading issues) the line which lists the domains included in that set of results was not showing - or was not clear. Anyway, I can see it is there now, so this is resolved.

**Comment by gustavo-salazar** [comment]
BTW, @Swaathik have added a documentation page for this tool, so @lorna if you can please have a look to it, you can see it in the dev machine: http://wp-np3-ab.ebi.ac.uk/interpro/about/ida/
