### ISSUE TITLE
Minor Issues: Search By Text

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#214]
These are some minor issues still pending from the sign-off document:

* Text Search Block and Help Block: somehow show this is for "more info"

**Comment by gustavo-salazar** [comment]
The icon to make the *Text Search Block* and *Help Block* visible was changed to the info icon... is that enough for this? @happy-lorna

**Comment by happy-lorna** [comment]
sounds like it should be but can you remind me where these are?

**Comment by gustavo-salazar** [comment]
So if you go to https://www.ebi.ac.uk/interpro/search/text/ at the side of the search block there is an icon ℹ️ that toggles the 2 info boxes.
THe ivon used to be a `>` and that's what I'm guessing was this issue about.

Also notice the icon drops to the next row when the screen is not wide enough, I already have fixed that in another issue.

**Comment by happy-lorna** [comment]
ah hah! yes that is better thanks!
would be _perfect_ if there were a tiny gap between the grey box and the info icon... (sorry)

**Comment by gustavo-salazar** [comment]
OK all changes now deployed in dev: http://wp-np3-ab.ebi.ac.uk/interpro/search/sequence/
