### ISSUE TITLE
Minor Issues: Browse Set

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#217]
These are some minor issues still pending from the sign-off document:

* For Pfam at least - it would be more informative to use the "Description" as the name rather than the ID. 
* Also PANTHER does have names (at least for some) can we use those instead of the accession.

**Comment by Swaathik** [comment]
This is same as the issue #221, isn't it?

**Comment by gustavo-salazar** [comment]
Yes and no! 😝
It would probably be the same fix, but one is about the list displayed in the browse area, and the other is once a set is selected, the info in its page.

**Comment by Swaathik** [comment]
Got it now :)

**Comment by happy-lorna** [comment]
Yeah I think I just covered this in the other thread. Just to say though - I am happy with how the results look in the browse table view now!
