### ISSUE TITLE
Minor issues: Entry Page

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#220]
These are some minor issues still pending from the sign-off document:

* the counter next to the Protein tab title does not match the number of protein matched in the table. see IPR000014 as example. 489k vs 504k.
* Domain Architecture title: if we are only showing the matches for this entry we should call this "match location(s)" rather than domain architecture.
* Domain Architecture: we should be clear on describing what this is - "Pfam architecture"
* Taxonomy - Key Species: The number of proteins doesn't always match the page when you follow the link: e.g. https://www.ebi.ac.uk/interpro/entry/InterPro/IPR000014/taxonomy/uniprot/#table

**Comment by gustavo-salazar** [comment]
I found what the issue is about the difference with the numbers: 
In the table it shows how many proteins have an exact match with the tax_id, but the list page, where is linked, uses the lineage, so a match with a child taxon is also included.

**Comment by gustavo-salazar** [comment]
This was an API issue. I va pushed the change to the dev branch of the API repo, but this won't be deployed until a new release date, as this will require changing the cache both in redis and in the clients.

**Comment by gustavo-salazar** [comment]
About the Domain architecture issues: @happy-lorna not sure the title change actually applies? and is the switch between pfam/interpro enough of should we add a description here explaining that we are using pfam to calculate domain architectures?

**Comment by happy-lorna** [comment]
re: Domain architecture title - This tool now appears to work how I would expect and so the title is fine. I think it was previously getting stuck and so giving partial results, that were not full architectures.
Pfam info - given that the description above explicitly states it uses Pfams, and the toggle is there between InterPro and Pfam, again this is now fine. 
I would change the wording of the description to this however:
"Domain architectures are derived from matches to Pfam models. You can select domains to either be included or excluded from your search results. The results will include all proteins which match the domain architecture selected below. Domains can be selected using either a Pfam accession, or an InterPro accession, where that InterPro entry includes a Pfam model."

**Comment by gustavo-salazar** [comment]
Changes now in Live: https://www.ebi.ac.uk/interpro/search/ida/
