### ISSUE TITLE
Minor issues: Set Page

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#221]
These are some minor issues still pending from the sign-off document:

* Pfam - use description for name. PANTHER - name is available, can we not use it?

**Comment by gustavo-salazar** [comment]
@matthiasblum I remember having a discussion about panther names. do you remember whats the situation there?

**Comment by Swaathik** [comment]
In the actual page for Pfam entry, we do have the description mentioned. If we use it instead of the name, won't it be repetitive?

**Comment by happy-lorna** [comment]
I think I was referring to the set network view page. 

On the Pfam page - as well as a name at the top, there is a field called description where we have the description of the clan. This is fine.
http://wp-np3-ab.ebi.ac.uk/interpro/set/pfam/CL0005/?search=#table

On the PANTHER page this description field doesn't exist as we don't have this info for Panthers. However I think we should add it and use the name of the "set" as used in the table result - in this case "PHOSPHOSERINE PHOSPHATASE". I realise in the case of Panther this is repetitive as the name is at the top of the page anyway - but it took me a while to spot that, so we might as well have it under description as well.
http://wp-np3-ab.ebi.ac.uk/interpro/set/panther/PTHR10000/?search=#table
