### ISSUE TITLE
searching interpro entries on google doesn't work

### ISSUE THREAD

**Issue by gsn7** [ProteinsWebTeam/interpro7-client#223]
it used to be the case with the old website that if I search an interpro entry on google it would give me the entry page. 
but if I try to search for example  IPR043504, IPR043476, IPR043220  i don't get  to the interpro entry pages.

**Comment by gustavo-salazar** [comment]
Sitemaps were created and the structure data that google and other search engines read have been updated. so it's just a matter of time to let google index the pages.
Closing the issue now, as that's all what we can do from our side
