### ISSUE TITLE
Add links to InterPro webinars in tutorial section

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#234]
Links are the following:
- Understanding InterPro families, domains and functions: https://www.ebi.ac.uk/training/online/course/understanding-interpro-families-domains-and-functions
- Using the InterPro website in your research: https://www.ebi.ac.uk/training/online/course/using-interpro-website-your-research
- Accessing InterPro programmatically: https://www.ebi.ac.uk/training/online/course/accessing-interpro-programmatically

Images for illustration:
![interpro_logo_blue](https://user-images.githubusercontent.com/25660657/82812787-aa1ea800-9e8b-11ea-9066-8dc3746c64e5.png)

![blog_newinterpro](https://user-images.githubusercontent.com/25660657/82812785-a854e480-9e8b-11ea-825e-4b26deaedb3c.png)

![tool_api_logo](https://user-images.githubusercontent.com/25660657/82812781-a723b780-9e8b-11ea-9734-ef8654597920.png)

**Comment by gustavo-salazar** [comment]
I think this has been completed as you can see it in: https://www.ebi.ac.uk/interpro/help/webinar/

We can reopen it if there is anything missing.
