### ISSUE TITLE
Protein viewer not displayed for proteins without member database matches but with other types of matches

### ISSUE THREAD

**Issue by matthiasblum** [ProteinsWebTeam/interpro7-client#235]
Some proteins are not hit by any member database signatures (and therefore not by any InterPro entries), but have sequence features (e.g. MobiDB Lite, Phobius, etc.).

For these proteins, the sequence viewer is not displayed on the protein page; instead the following message is shown:

> No entries match this protein.

Example: [A0A009DX03](https://www.ebi.ac.uk/interpro/protein/unreviewed/A0A009DX03/) ([legacy website](https://www.ebi.ac.uk/interpro/legacy/protein/A0A009DX03/)).

It would be nice to display the extra sequence features, even if there are not member database matches.

**Comment by gustavo-salazar** [comment]
OK so I'm fixing this, and testing these scenarios:
1. No entry matches, no extra features. e.g. A0A009DWB1
2. No entry matches, but there are extra features. e.g.  A0A009DX03
3. Entry matches, not extra features. e.g. A0A000
4. Entry matches and extra features. e.g. A0A001

@matthiasblum @gsn7 any other scenario I should consider?
