### ISSUE TITLE
Pfam entries of repeat type are not included while showing the conservation score

### ISSUE THREAD

**Issue by Swaathik** [ProteinsWebTeam/interpro7-client#239]
Example https://wwwdev.ebi.ac.uk/interpro/protein/reviewed/Q7Y1C5/ - The sequence conservation of entry PF00634 is not present in the fetch conservation track

**Comment by gustavo-salazar** [comment]
@Swaathik I just noticed it works ok in wwwdev but is still not working in live. Does it need anything from the API? or am I missing something?

Also somehow using the conservation button is sort of unstable, sometimes gives errors, sometimes just don't load anything and sometimes just work... not sure what's going on

**Comment by Swaathik** [comment]
No, it did not require any change in the API. I had to add the repeat type while we merge the results in our code. 

They both look different though. Even the protein family membership is none in the live version and there are less number of tracks for this protein - https://wwwdev.ebi.ac.uk/interpro/protein/reviewed/Q7Y1C5/

**Comment by gustavo-salazar** [comment]
Changes now in live: https://www.ebi.ac.uk/interpro/protein/reviewed/Q7Y1C5/
