### ISSUE TITLE
The interaction controllers in the signature page has errors

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#240]
There are multiple issues when interacting with the logo visualization.
https://www.ebi.ac.uk/interpro/entry/pfam/PF00040/logo/

* the settings close their popup when selecting a different option, and it doesn't actually selects the function.
* The column number input, is not working and instead of jumping to the desired position, repaints the graphic.
* If the column number has been selected, the probability values under the graphic lose their colors.

**Comment by CodeGit** [comment]
merged into master
