### ISSUE TITLE
Description in the search results needs encoding

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#241]
When a user does a trext search, the column for description has some characters that need encoding. 
e.g. https://www.ebi.ac.uk/interpro/search/text/UP000005640/#table

![Screenshot 2020-07-07 at 10 00 22](https://user-images.githubusercontent.com/46671268/86759335-5da6ba80-c03c-11ea-97b7-1bdb3d8d8311.png)

**Comment by gustavo-salazar** [comment]
after the encoding, its clear that most of the weird characters were html tags, specifically `<p> </p>`. we should remove them. for the description of the search results.

**Comment by Swaathik** [comment]
I noticed three tags occurring - <p>(In all of them), <ul>, <li>. I have included these three in the regex. Is there anything else we have to check?

**Comment by gustavo-salazar** [comment]
I think that should be it for now... in reality this is just an extract of the description so it doesn't matter that it renders perfect evry time, but as you said the `<p>` were in all of them and that makes it look bad in general... may be put a comment in the code, so if we get another on that is annoying we can easily add it there later.
