### ISSUE TITLE
PDB entries in lower case

### ISSUE THREAD

**Issue by gsn7** [ProteinsWebTeam/interpro7-client#28]
PDB lists their entries in lower case, and we have them in upper case, is this by design?
I prefer to keep the terms in their original format from their sources unless it breaks something on our side

**Comment by 4ndr01d3** [comment]
As a policy now we will keep the case of the DB provider, and so this should be apply on the API for all endpoints

**Comment by 4ndr01d3** [comment]
Now the API returns the accession as it's in the MySQL DB. And the client doesn't modified.
In`dev` branch, to be deployed in the next release
