### ISSUE TITLE
Add download link to InterProScan search results

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#303]
Users should be able to download the results from an InterProScan search in the Results tab

**Comment by Swaathik** [comment]
Related to this, the export button in the InterProScan result has got disabling/enabling functionality depending on the scenario. It is included in the PR #306

**Comment by gustavo-salazar** [comment]
Button added and to be release soon. for now in staging: https://wwwdev.ebi.ac.uk/interpro/protein/UniProt/P00734/
