### ISSUE TITLE
See contact when hovering over the AA in the sequence

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#315]
It would be great if we could also see the contacts when hovering over the AA in the sequence (especially when the SEED contains a lot of sequences, when scrolling down the 3D viewer is shown but we can't interact with it from the sequence, when at the very bottom of the page, see screenshot).

**Comment by gustavo-salazar** [comment]
I marked as stalled, until a decision is taking about unification of the several structural model sources

**Comment by gustavo-salazar** [comment]
RosettaFold models were removed, and the contacts viewer was only available there.
So, I'm closing this issue
