### ISSUE TITLE
Key Species

### ISSUE THREAD

**Issue by EBI-Hsinyu** [ProteinsWebTeam/interpro7-client#32]
I would be useful to have key species in the taxonomy page. 
https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR040000/taxonomy/uniprot/?search=Saccharomyces%20cerevisiae#table

**Comment by 4ndr01d3** [comment]
A table with key species on all taxonomy subpages has been added.
To be deployed together with a new API version, later this week.
