### ISSUE TITLE
Add 3D structure quality colour scale

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#349]
The 3D structure is coloured by per-residue pLDDT score with a rainbow gradient going from blue (high quality) to red (low quality), it would be nice too add the colour scale somewhere on the structure page and also for the structural models.

**Comment by gustavo-salazar** [comment]
I marked as stalled, until a decision is taking about unification of the several structural model sources

**Comment by gustavo-salazar** [comment]
We now have the LDDT track in all proteins. And have removed the other model pages. so I'm going to close this issue.
Feel free to reopen if you think I'm missing something.
