### ISSUE TITLE
IPR015813 doesn't appear to cover protein correctly (may be data issue)

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#35]
IPR015813 is based on SSF51621 but the two appear differently in the protvista viewer

From: https://www.ebi.ac.uk/interpro/beta/protein/UniProt/P30613/

<img width="1158" alt="screen shot 2018-10-05 at 13 23 14" src="https://user-images.githubusercontent.com/892047/46535123-50c2c900-c8a2-11e8-8171-e2a621795412.png">

**Comment by 4ndr01d3** [comment]
After following the link these have been fixed with latest API release
