### ISSUE TITLE
Add trRosetta models to IPR pages with integrated Pfams

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#355]
I am quite happy to see InterPro's Pfam pages like https://www.ebi.ac.uk/interpro/entry/pfam/PF06316/ coming with a trRosetta prediction, but the same prediction is not shown on the IPR page of https://www.ebi.ac.uk/interpro/entry/InterPro/IPR000758/. Maybe the IPR pages should show the trRosetta results for member Pfam families too?

**Comment by gustavo-salazar** [comment]
This has been added and merge into live
