### ISSUE TITLE
References not properly displayed

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#361]
I've noticed that when there is no space between two references in entries descriptions, there aren't displayed properly.
Here is an example: [https://www.ebi.ac.uk/interpro/entry/InterPro/IPR011364/](https://www.ebi.ac.uk/interpro/entry/InterPro/IPR011364/)

**Comment by gustavo-salazar** [comment]
This has been resolved and merged into master
