### ISSUE TITLE
Add favourite sequence feature

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#363]
It would be great to add a favourite sequence feature in sequence search, allowing the sequence searched to be kept and searched again when a new InterPro release is available (similar to what is provided in the new (beta) UniProt website).

**Comment by gustavo-salazar** [comment]
@typhainepl do you have a link in uniprot to see it working, or please explain me how do you use it there. I did a search and saved the results but I don't know where to save the sequence

**Comment by gustavo-salazar** [comment]
Is it the resubmit this job Icon in the results page?

**Comment by typhainepl** [comment]
I was referring to the star icon, which allows the sequence to be saved forever (like the InterPro entry favourite option) and then run again when a new InterProScan version is available. But I guess that is similar to saving the research results and run InterProScan again. However, it will be nice to have a shortcut to run the analysis again in the overview page when the results were obtained using a different version of InterProScan, without having to go to sequence> Run InterProScan.
