### ISSUE TITLE
Fix Genome3D matches displayed twice for InterPro entries

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#364]
The Genome 3D matches are sometime displayed twice in the table for InterPro entries: once with the id and another time without.
This happens when there are both predicted domain and predicted 3d structure in genome3D, I think we should only show the matches to predicted domains.
Example: https://www.ebi.ac.uk/interpro/entry/InterPro/IPR000003/genome3d/?sort_by=accession#table
http://www.genome3d.net/uniprot/id/P20153/annotations

**Comment by gustavo-salazar** [comment]
The Genome3D subpage was removed, hence I'm closing this issue
