### ISSUE TITLE
Binding pocket annotations missing

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#366]
Since the addition of the Residue track in the protein sequence viewer, the binding pocket residue annotation (cd00201) for [O00308](https://www.ebi.ac.uk/interpro/protein/UniProt/O00308/) isn't displayed anymore.
See a similar protein with the residues: [A2A5Z6](https://www.ebi.ac.uk/interpro/protein/reviewed/A2A5Z6/)

**Comment by matthiasblum** [comment]
This is a data issue rather than a client-related issue. Binding pocket residue annotations were not propagated to the data warehouse. I'll investigate whether we can fix the issue before the next release.

**Comment by matthiasblum** [comment]
Fixed in release 88.0.
