### ISSUE TITLE
Top banner search improvements

### ISSUE THREAD

**Issue by sebpca** [ProteinsWebTeam/interpro7-client#37]
After entering a search term and clicking the search icon, it should keep the search term result page (for the moment it redirects to search page and doesn't "keep" the search term - does a page refresh).

Also when entering a search term, he would like to keep the focus on the search term in the banner, even when you visit other pages.

reported from @gift

**Comment by 4ndr01d3** [comment]
FIxed: Search Icon now has the term.

Keeping the search term beyond the search result page requires more discussion. On the UX side it can be misleading to have that search there after moving away. On the technical side, the textbox is linked to the data from the redux state, so if that is the desired behaviour it requires to refactor that component
