### ISSUE TITLE
Per residue position incorrect in tooltip when more than one residue.

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#372]
Some of the member databases provide a set of residues as part of their per residue annotations, but at the moment we only display the first in the tooltip.

The idea will be to test if the start and end positions provided are the same:
- if yes: display the residue position
- if not: display the residues range

ex: https://www.ebi.ac.uk/interpro/protein/reviewed/P43403/ (NP_BIND: ATP).
Additionally, in this example the PIRSR residue annotation looks like it belongs to the CDD signature, it would be great to find a way to separate them in the display.

**Comment by gustavo-salazar** [comment]
Deployed on dev for testing

**Comment by typhainepl** [comment]
working fine, but with the new left menu the view is shifted to the right on my screen
e.g. http://wp-np3-aa.ebi.ac.uk/future/protein/UniProt/P43403/
![image](https://user-images.githubusercontent.com/25660657/165352940-d4573f34-0d66-4a27-ace2-18f6f389403e.png)

**Comment by typhainepl** [comment]
I also noticed that sometimes the domain residues are mapping are coloured in the same colour as the one used in the domains section, but other times they just appear in grey.
