### ISSUE TITLE
SEED alignment not loading in RoseTTAFold page

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#376]
SEED alignment not loading in RoseTTAFold page for https://www.ebi.ac.uk/interpro/entry/InterPro/IPR005877/rosettafold/

This has been reported by a user on interhelp: https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=549055

**Comment by gustavo-salazar** [comment]
This has been fixed and it's now live. e.g. https://www.ebi.ac.uk/interpro/entry/InterPro/IPR005877/rosettafold/
Cached has been cleared and the request to refresh the client's cache has also been sent.
