### ISSUE TITLE
Menu highlight issue in InterProScan result page

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#379]
The menu for InterProScan search results (Overview / Entries /Sequence) makes the current selected tab name unreadable.

![image](https://user-images.githubusercontent.com/25660657/162169309-84f60413-adf3-4d21-87b7-e47eac49d1e3.png)

**Comment by gustavo-salazar** [comment]
Indeed, there is a problem there. I'll fix it.
Basically 2 css rules have the same specificity, and it ends up going for whatever gets loaded first. That order changed with the recent changes in the webpack config. i've seen this problem in other places and I have corrected it, but please keep an eye to any weird style changes recently. if you noticed any maybe just mention them here.

**Comment by typhainepl** [comment]
Thanks for looking into that. Sure, I will add other issues when encountered here.

**Comment by typhainepl** [comment]
changes are working well on my side
