### ISSUE TITLE
Entry counter on Proteome page should show same value as Entry table

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#38]
The counter shows 22k but the table only shows 6k (because InterPro is selected). Rob would like the top counter to change whenever the member database is selected.

<img width="574" alt="screen shot 2018-10-09 at 12 41 10" src="https://user-images.githubusercontent.com/892047/46667296-22562e00-cbc1-11e8-96bb-86b79f097af2.png">

**Comment by 4ndr01d3** [comment]
We now default this number to the count of Interpro entries. Which makes that the list shown just after clicking on it matches the number because interpor is the default.
Once another DB is selected, the number there gets updated by the corresponding count.
