### ISSUE TITLE
Set/Entries TotalNb

### ISSUE THREAD

**Issue by sebpca** [ProteinsWebTeam/interpro7-client#40]
Remove the option to select Member database (as it is not  feasible for sets):
![image](https://user-images.githubusercontent.com/11173535/46953341-85463a00-d085-11e8-9fdc-143aa87e2b2d.png)

**Comment by sebpca** [comment]
Same for the InterProScan search result page:
![image](https://user-images.githubusercontent.com/11173535/47161089-31d42600-d2e9-11e8-9659-3e16ec69f0fe.png)

**Comment by 4ndr01d3** [comment]
The InterProScan part has been fixed.

**Comment by 4ndr01d3** [comment]
Done and to be in the beta  in next deploy
