### ISSUE TITLE
print functionality for sequence viewer is broken

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#408]
[P18207 (P18207) - protein - InterPro.pdf](https://github.com/ProteinsWebTeam/interpro7-client/files/9547227/P18207.P18207.-.protein.-.InterPro.pdf)
example: https://www.ebi.ac.uk/interpro/protein/UniProt/P18207/

**Comment by gustavo-salazar** [comment]
Hey,
On first look, It seems tome that it's related to the CSS rules on different screen sizes.
So, not a solution, but a workaround in the meantime, if you need to get it to print to get the pdf, change the size of your window and try again.

**Comment by typhainepl** [comment]
What do you mean by "change the size of your window"?
I've zoomed the page out by 50% on my laptop screen and still have a similar issue
[P18207 (P18207) - protein - InterPro.pdf](https://github.com/ProteinsWebTeam/interpro7-client/files/9549085/P18207.P18207.-.protein.-.InterPro.pdf)

**Comment by gustavo-salazar** [comment]
Sorry, I didn't mean zooming but changing the width of the window to around 600px. This somehow doesn't have the text overlapping the features, however the navigation bar is now out of sync with the rest of the graphic.

Of course, this is not a fix and I'll have a look at what's causing the problem.

**Comment by typhainepl** [comment]
I wanted to use it to generate a figure for the InterPro NAR paper, but it won't work.
For some reason it also wants to print the entry name while in the viewer I have only selected the accession to be displayed.
Could you also look into that?

**Comment by typhainepl** [comment]
No actually after looking closer it doesn't print the name, but the path to the entries ...
[P18207 (P18207) - protein - InterPro.pdf](https://github.com/ProteinsWebTeam/interpro7-client/files/9555810/P18207.P18207.-.protein.-.InterPro.pdf)

**Comment by gustavo-salazar** [comment]
Hey @typhainepl can you please confirm if this is still an issue with the most recent release

**Comment by typhainepl** [comment]
The problem has been resolved, except for Pfam-N annotations

**Comment by gustavo-salazar** [comment]
Mh I didn't notice those, cool I'll see what's happening there
