### ISSUE TITLE
Favicon.. is gone

### ISSUE THREAD

**Issue by sebpca** [ProteinsWebTeam/interpro7-client#41]
Need to change the way we deal with the favicon in the Webpack.config.js (doesn't work when trying to include this `' <link rel="apple-touch-icon" sizes="57x57" href="/images/logo/favicon/apple-icon-57x57.png" />
    <link rel="apple-touch-icon" sizes="60x60" href="/images/logo/favicon/apple-icon-60x60.png"/>
    <link rel="apple-touch-icon" sizes="72x72" href="/images/logo/favicon/apple-icon-72x72.png"/>
    <link rel="apple-touch-icon" sizes="76x76" href="/images/logo/favicon/apple-icon-76x76.png"/>
    <link rel="apple-touch-icon" sizes="114x114" href="/images/logo/favicon/apple-icon-114x114.png"/>
    <link rel="apple-touch-icon" sizes="120x120" href="/images/logo/favicon/apple-icon-120x120.png"/>
    <link rel="apple-touch-icon" sizes="144x144" href="/images/logo/favicon/apple-icon-144x144.png"/>
    <link rel="apple-touch-icon" sizes="152x152" href="/images/logo/favicon/apple-icon-152x152.png"/>
    <link rel="apple-touch-icon" sizes="180x180" href="/images/logo/favicon/apple-icon-180x180.png"/>
    <link rel="icon" type="image/png" sizes="192x192"  href="/images/logo/favicon/android-icon-192x192.png"/>
    <link rel="icon" type="image/png" sizes="32x32" href="/images/logo/favicon/favicon-32x32.png"/>
    <link rel="icon" type="image/png" sizes="96x96" href="/images/logo/favicon/favicon-96x96.png"/>
    <link rel="icon" type="image/png" sizes="16x16" href="/images/logo/favicon/favicon-16x16.png"/>
    <link rel="manifest" href="/images/logo/favicon/manifest.json"/>
    <meta name="msapplication-TileColor" content="#ffffff"/>
    <meta name="msapplication-TileImage" content="/images/logo/favicon/ms-icon-144x144.png"/>
    <` ' in the index.template

**Comment by 4ndr01d3** [comment]
Recovered. There was a bug in webpack about the order the plugins were getting loaded.
We upgraded webpack to `4.22.0` And made sure `html-webpack-plugin` gets loaded first.
