### ISSUE TITLE
Pfam sets on the InterPro website

### ISSUE THREAD

**Issue by blazaropinto** [ProteinsWebTeam/interpro7-client#416]
As discussed, just to leave all this written:

-curators really miss to see the short names of the families that are members of a clan all together (could an extra column be added [here](https://www.ebi.ac.uk/interpro/set/pfam/CL0001/entry/pfam/#table) please?)  :) :)

-we were discussing about the need for a "clan alignment" file (for a user to be able to see/download the alignments of all the family members all at once -in the pfam website that was possible for small clans... not sure if that's useful though..)

-just a thought... personally I miss the "example structure image" as I go to a Pfam entry in InterPro... not a problem at all for me but just saying maybe other users also do? not sure..

**Comment by gustavo-salazar** [comment]
Hey @blazaropinto we were discussing these points today.
* The page with all the sequence alignments on a set required a lot of preprocessing during release, so it is unlikely to be re-integrated in InterPro.
* I'll work o adding the example structure to the entry pages. hopefully we'll have this future in the next release.

**Comment by gustavo-salazar** [comment]
Hey @blazaropinto the representative structure is finally seeing the light in the website. For now only in the `dev` environment: http://wp-np3-bd/interpro/entry/pfam/PF00051/ but it will be included in the next release

**Comment by blazaropinto** [comment]
That looks great @gustavo-salazar ! 👏 :D
