### ISSUE TITLE
Structure page improvements

### ISSUE THREAD

**Issue by sebpca** [ProteinsWebTeam/interpro7-client#42]
In Protvista sequence viewer, the "Chain" doesn't highlight itself on the protein 3D view (on mouse over).

When several chains on several protein: it would be nice to show the protein Accession number next to "Chain" title, to understand if we are looking at different proteins (e.g.1A6A).

**Comment by 4ndr01d3** [comment]
The protein accession is added.
I'll add the highlighting of the chain once we fixed the issue with the coordinate mapping.

**Comment by 4ndr01d3** [comment]
Chain now highlights the structure. On dev brach for now
