### ISSUE TITLE
Add the option to colour 3D structure by hydrophobicity property

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#420]
This has been requested by a trainee in the Structural bioinformatics course.
We could imagine having an option to colour the residues in the 3D viewer by LDDT score or hydrophobicity property.
This could be implemented for AF, RoseTTAFold and PDB structures.

**Comment by gustavo-salazar** [comment]
Given that we removed the hydrophobicity track, I don't think this makes sense any more. 
If we bring back that track we can reopen this issue
