### ISSUE TITLE
Enable search for member database and InterPro short names and get exact match

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#429]
The search by short name was a feature of the Pfam website.

**Comment by gustavo-salazar** [comment]
@matthiasblum @typhainepl  I'm working on getting an exact match similar to what you get with protein names like in https://www.ebi.ac.uk/interpro/search/text/piwi/?page=1#table 

My first attempt is to extend the functionality in the `utils/accession/` endpoint so for example https://www.ebi.ac.uk/interpro/api/utils/accession/7tm_3 should return something like:
```js
{
    "endpoint": "entry",
    "entries": [
        {
            "accession": "PF00003",
            "source_database": "pfam"
        }
    ]
}
```

1. For this to work, we are going to need an index in the `entry` table by its `short_name` column.
2. Currently that endpoint looks by
    1. `accession` in all endpoints - using elastic
    2. `protein.identifier` - using MySQL
    3. `protein.gene` for key species - using MySQL
    
    For performance's sake, we stop searching when we find something. So for example we don't query MySQL if we got a result from Elastic.

    So the search by `entry.shot_name` will be another one in this list. However, there are cases where the search term might be both a `protein.gene` and an `entry.short_name`, so this strategy of stopping when finding something might not be ideal. So we need to decide what to do
    1. Do all the searches and give a combined response, which will affect the performance when searching for accessions, and will require changes in the client to deal with a new format.
    2. Ignore that case and prioritise one exact search over another. Simple to develop but the user might not get the expected results.
    3. Create another endpoint `utils/short_name` or something and execute another API request for this info.

    Any opinions?

**Comment by matthiasblum** [comment]
ProteinsWebTeam/interpro7-api#115.
