### ISSUE TITLE
Not all interactions between ProtVista and Litemol work as expected

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#43]
https://www.ebi.ac.uk/interpro/beta/structure/PDB/1a0h/

Mouseover on IPR009003 does not highlight anything in the litemol view. Selecting it from the dropdown above works fine.

**Comment by 4ndr01d3** [comment]
The mentioned structure doesn't cover the whole protein, and therefore there are going to be entries that won't highlight
