### ISSUE TITLE
Add a list of updated entries additionally to the latest entries

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#430]
It would be nice to have a list of the updated entries for each release. E.g. if the name, description or member db have changed.

**Comment by gustavo-salazar** [comment]
This info is not available at the moment in the API. @matthiasblum do you think this is feasible?

**Comment by matthiasblum** [comment]
> This info is not available at the moment in the API. @matthiasblum do you think this is feasible?

Yes, it's feasible, however to what end we would need this @typhainepl? I don't think it makes a lot of sense to show such a list to users.
