### ISSUE TITLE
enable search for “former short names”

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#431]
Reported by Beatriz:
Another feature of the Pfam website was to be able to search by “former short names” and obtain the corresponding Pfam.
Not sure how feasible it is in the InterPro organisation.

**Comment by blazaropinto** [comment]
The comment above was specially thinking of former DUFs (as not always is that simple/quick to find elsewhere the accession or the current name- I don't know if users would notice this, for clarification)

Another comment related to the Search by text in InterPro (not sure if this one is relevant):
when searching part of a word, not all entries containing this half-word are shown in the results table. As an example, when searching for "Nesprin-1" or "Nesprin", the entry named "Nesprin-1-like, first calponin homology domain" does not appear in the results table.

**Comment by blazaropinto** [comment]
The second issue seems to be ok now

**Comment by gustavo-salazar** [comment]
Former short names are not currently available in the API nor in the EBI search index. @matthiasblum how feasible would be to add them?

**Comment by blazaropinto** [comment]
This is the github issue I was talking about in the stand up today

**Comment by matthiasblum** [comment]
@blazaropinto This is now possible, e.g. [DUF290](https://wwwdev.ebi.ac.uk/interpro/search/text/DUF290/#table).
