### ISSUE TITLE
InterProScan/Entry result page

### ISSUE THREAD

**Issue by sebpca** [ProteinsWebTeam/interpro7-client#44]
- Double blob on Protvista (first two lines only)
![image](https://user-images.githubusercontent.com/11173535/48127151-f2ab4c00-e27a-11e8-823c-1fd123d8bb17.png)

https://wwwdev.ebi.ac.uk/interpro7/job/InterProScan/iprscan5-R20181107-103706-0685-42070164-np2/entry/InterPro/#table

- Export button (API) is not working:
https://wwwdev.ebi.ac.uk/interpro7/api/job/InterProScan/iprscan5-R20181107-103706-0685-42070164-np2/entry/InterPro/?page_size=100 

It says  "Error": "the level 'job' is not a valid home level"

**Comment by 4ndr01d3** [comment]
This data doesn't come from the API.
I have removed the export button on the entry table

BTW. The user can still download the info from the Export button on the overview page.
