### ISSUE TITLE
Add link to sequences in Pfam alignments

### ISSUE THREAD

**Issue by sarach06** [ProteinsWebTeam/interpro7-client#441]
It would be useful to have the link to sequences in Pfam alignments or the possibility of selecting/copying the accession ID, at least for the SEEDs (sometimes full alignments are huge)

**Comment by gustavo-salazar** [comment]
Ok I'm looking at using the labels at the left-hand side of the alignment as links to the protein page. For example, in [this alignment](https://www.ebi.ac.uk/interpro/entry/pfam/PF00002/entry_alignments/?type=seed) the label `PACR_MOUSE` will be a link to the protein page. Do you think is better to link to [Overview](https://www.ebi.ac.uk/interpro/protein/reviewed/P70205/) or to [Sequence](https://www.ebi.ac.uk/interpro/protein/reviewed/P70205/sequence/) directly

**Comment by sarach06** [comment]
Thanks! I think to overview is more informative (and nicer) and all the other useful links are there.
