### ISSUE TITLE
No search results found 404

### ISSUE THREAD

**Issue by DraLaylaHirsh** [ProteinsWebTeam/interpro7-client#442]
Used Firefox to search on google page " interpro PF00064 "
![search](https://user-images.githubusercontent.com/111517699/206665527-b3694583-cb02-4a03-bdbd-52dd993a65ee.png)
64
Clicked on the first result, and got that error

![ERRORNoSearchResults](https://user-images.githubusercontent.com/111517699/206665122-229d858c-ce36-462c-9ad8-59950a9fde88.png)

after a while the results were retrieved correctly

**Comment by gustavo-salazar** [comment]
Thanks for reporting. I have requested the update in the google index. 
I'll check this in a few days to see if this has been corrected

**Comment by gustavo-salazar** [comment]
OK so the reported wrong URL has been removed from google, but now there is no match for such a search in InterPro. 
I have updated the sitemap and included Pfam entries, but this might take a few weeks before google reindex all those URLs. 
I'm closing this issue, as not further action will be necessary, but please reopen if in a few weeks we still don't get google results pointing at InterPro
