### ISSUE TITLE
Bulk download of AF models for signatures

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#453]
A user asked if it was possible to bulk download AF models for a particular signature/entry.
I think this could be an interesting feature to add.

**Comment by gustavo-salazar** [comment]
@matthiasblum answered the user with instructions on how to create a script to get this information.
Do you think that's enough for this ticket? Or should I've been thinking about where to add something to trigger that functionality?

TBH I don't think is a feature many people will take advantage of.

**Comment by matthiasblum** [comment]
I think the ticket can be closed.
