### ISSUE TITLE
Reorganise sequence viewer for sequence search results

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#455]
At the moment CATH funfams are displayed in the "Unintegrated" section of the sequence viewer.
Since we are never going to integrate them into InterPro entries, it is not correct to have them in that category.
My suggestion is to rename the "Prediction" category to "Other features" and move the CATH funfams matches to this category.

**Comment by gustavo-salazar** [comment]
OK so working on this. I have so far moved `funfam` matches into _Other Features_ and `pirsr` into _Other Residues_.
Are there other types of matches that should be included in these categories?

**Comment by gustavo-salazar** [comment]
Sure thing
