### ISSUE TITLE
Create an overlap threshold for structures and Interpro entries

### ISSUE THREAD

**Issue by tony787** [ProteinsWebTeam/interpro7-client#456]
Example the Interpro entry below:
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR001762/structure/PDB/#table
where the pdb entries 1zxc and 2a8h are displayed and counted despite there is an overlap of only 2 residues between these structures and the Interpro entry.
Overlap threshold of 5 or 10 residue can be used to filter cases like the one above.

**Comment by laisecf** [comment]
Hi, Toni!! To help with the overlap threshold decision we created this plot:

<img width="585" alt="Screenshot 2023-03-23 at 10 45 22" src="https://user-images.githubusercontent.com/17861151/227179744-88be2c5d-6acf-4c02-940f-b97be394d0a7.png">

We can create the threshold considering two ways:
- the distribution of overlaps between structures and the Interpro entry; or
- the proportional overlap between structures and the Interpro entry and the length of segments (formula: ` overlap_len/min(loc_len, seg_len)`)

Based on that, which way and which threshold do you prefer to consider? 
Thank you!

**Comment by tony787** [comment]
Hi Laise,
I believe having a small test set with different sequence length (small, medium, long) and with the two approaches applied would probably help to choose the better way. I'm happy to look at the result.
Thanks!

**Comment by laisecf** [comment]
Hi Toni,

Considering the sequence sizes
 - short: 200 residues or less
 - medium: between 201 and 500 residues
 - long: greater than 500 residues
 
we have the following plots for each approach:

![overlap_plot](https://user-images.githubusercontent.com/17861151/227926893-d143c861-72fe-4484-ab26-6bf607c6b5e7.png)
![proportional_overlap_plot](https://user-images.githubusercontent.com/17861151/227926901-c319196c-1e23-4e04-93b6-5f4ca4d95a72.png)

Hope that helps, but let me know if there's any other analysis I can do to help with the decision.

**Comment by laisecf** [comment]
Hi Toni!!

Now considering the sequence sizes

short: 80 residues or less
medium: between 81 and 500 residues
long: greater than 500 residues

we have the following plots for each approach:

![basic_overlap](https://user-images.githubusercontent.com/17861151/228008954-73f2bc85-5f95-4b56-8f36-7d6d27b65dcc.png)
![proportional](https://user-images.githubusercontent.com/17861151/228008964-543ceb13-00d9-429e-ad3e-d850d42cdfc7.png)



------------------------------------------------------------------------------------------------------
Just as additional information (I don't know if it's useful), the distribution of sequences length:

![distribuction_length](https://user-images.githubusercontent.com/17861151/228010238-f3243ec4-2e93-40f6-82ef-c4ef36bb6300.png)

**Comment by laisecf** [comment]
https://docs.google.com/spreadsheets/d/1yYsMbBUHU1qC0o2SR3D08_2NtkrNAWcnMHMxUyIYgKw/edit#gid=0

**Comment by laisecf** [comment]
[same_len_pdb_seg_10_less.txt](https://github.com/ProteinsWebTeam/interpro7-client/files/11090109/same_len_pdb_seg_10_less.txt)
[same_len_interpro_loc_10_less.txt](https://github.com/ProteinsWebTeam/interpro7-client/files/11090111/same_len_interpro_loc_10_less.txt)

**Comment by tony787** [comment]
file1 with overlap <= 15 residues
file2 with proportional overlap <= 20%

**Comment by laisecf** [comment]
/hps/software/users/agb/interpro/lcf/gitprojects/interpro7-dw/proportion_20_less.txt
/hps/software/users/agb/interpro/lcf/gitprojects/interpro7-dw/overlap_15_less.txt

**Comment by laisecf** [comment]
Great! Thank you, Toni o/

**Comment by tony787** [comment]
I'm afraid I have to reopen this issue as the current fix is erroneous.
Here is an example : E4SK47 

in Interpro:
https://www.ebi.ac.uk/interpro/protein/UniProt/E4SK47/structure/PDB/#table

and in PDBe-KB
https://www.ebi.ac.uk/pdbe/pdbe-kb/proteins/E4SK47/structures

InterPro displays all structures mapped on the same region which is not the case.
Correct information is displayed by PDBe-KB

**Comment by matthiasblum** [comment]
@tony787, following the issue you opened yesterday, I had a look and I think we should be able to fix it soon.

**Comment by tony787** [comment]
ok. thank you. I wasn't sure the issue is reopen by simply submitting a comment (no reopen button) and therefore I created a new ticket.
