### ISSUE TITLE
Protein sequence doesn't get copied when clicking on "Search protein with HMMER"

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#462]

**Comment by gustavo-salazar** [comment]
This is an issue in HmmerWeb. I opened a PR there https://github.com/ProteinsWebTeam/HmmerWeb/pull/20  but this might take a while to make it into the main website

**Comment by gustavo-salazar** [comment]
We disabled the button until hmmerweb is more stable
