### ISSUE TITLE
The Wikipedia article for some Pfam entries isn't displayed

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#466]
Alex has found out that some Pfam Wikipedia articles are missing in the InterPro website.
Example: https://www.ebi.ac.uk/interpro/entry/pfam/PF00571/

http://pfam-legacy.xfam.org/family/PF00571

**Comment by gustavo-salazar** [comment]
The data is not in MySQL, so this is an issue upstream in the release procedures. @matthiasblum

**Comment by gustavo-salazar** [comment]
I think is likely this problem is solved with InterPro 94.
@typhainepl @matthiasblum can I close this issue?

**Comment by typhainepl** [comment]
Looks fixed indeed, you can go ahead.
