### ISSUE TITLE
Protvista - missing 1AA on the right hand sie

### ISSUE THREAD

**Issue by sebpca** [ProteinsWebTeam/interpro7-client#47]
It looks like we are missing the last amino acid for every sequence searched. The sequence is shown correctly on the sequence section, but miss one amino acid on the protvista sequence viewer.
![image](https://user-images.githubusercontent.com/11173535/48425035-dec08800-e75b-11e8-909e-65ac32946df2.png)

**Comment by 4ndr01d3** [comment]
Xavier just mentioned a similar issue in the component, and he is checking this. I'll wait until he has finish with it, to take the new version and see if it solves this issue

**Comment by 4ndr01d3** [comment]
Fixed in protvista. 
Now in `dev` branch
