### ISSUE TITLE
Implement functionality to generate domain images

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#470]
A [Pfam user](https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=648708&results=d3e209399fd7e41ab35ce6b5b7df9f7b) has asked whether or not we have an equivalent to the Pfam feature that allows to generate domain images: http://pfam-legacy.xfam.org/generate_graphic. I think it will be a good idea to have such feature implemented in InterPro.

**Comment by matthiasblum** [comment]
Available at https://proteinswebteam.github.io/domain-gfx/
