### ISSUE TITLE
Minor Issues with current `dev`

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#473]
The current dev branch includes the migration to TypeScript and the use of Nightingale components v4.0.

Here is a list of some minor issues found in it:

#### Protein Viewer
- [x] Labels over `interpro-tracks` are sometimes white when they should be black, or vice versa. They go to the right color after hovering.
- [x] Changing the `Color By` option in the protein viewer triggers an error.
- [x] Residues look blurry
- [ ] the print functionality doesn't work
- [x] the save as image is cut at the bottom
- [ ] the collapse all tracks for residues makes the text unreadable, also can you make it as it takes the colour of the top domain only (not superposition)? the text isn't always readable with the different colour shades superposed
- [ ] the collapse all tracks doesn't always work on the protein page
- [x] the secondary structure info is too small (e.g. http://wp-np3-aa.ebi.ac.uk/interpro/structure/PDB/2fo0/)
#### Alignment
- [x] Clickable link in the sequence name not working
- [x] Conservation option is missing
- [x] Make Legends blocks smaller
#### Alphafold viewer
- [ ] The colouring when hovering an entry behaved inconsistently, sometimes the unselected area changes to grey other and other time it keeps the confidence colouring
#### RosettaFold
- [x] Heatmap viewer side by side
- [x] Add PiP button
- [x] harmonize with buttons in other viewers.

**Comment by gustavo-salazar** [comment]
@typhainepl please check I got everything here, and let me know if you notice something else

**Comment by typhainepl** [comment]
A few more bugs I just spoted:The print functionality doesn't work, the save as image is cut at the bottom

**Comment by gustavo-salazar** [comment]
Closing this as the left issues have their own issue or story.
