### ISSUE TITLE
Conservation fetch doesn't work

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#478]
It looks like the Fetch conservation isn't working anymore, I get a 500 Error code.
Example: https://www.ebi.ac.uk/interpro/protein/UniProt/O75069/

**Comment by gustavo-salazar** [comment]
That fature depends on HmmerWeb, and their API is not responsive at the moment... I message them about it.

**Comment by gustavo-salazar** [comment]
Disabling this feature in the meantime
