### ISSUE TITLE
 History of "searched" terms

### ISSUE THREAD

**Issue by sebpca** [ProteinsWebTeam/interpro7-client#49]
If possible, it would be a nice and logic addition to keep the user "searched terms" - small history of searches using EBI text search - in the "Results" section, so you could have 3 submenus there:
Your InterProScan searches
**Your text searches**
Your downloads

**Comment by gustavo-salazar** [comment]
Feature deployed in live in version [v1.9.0](https://github.com/ProteinsWebTeam/interpro7-client/releases/tag/v1.9.0)
