### ISSUE TITLE
Proteins without entry matches never fully load

### ISSUE THREAD

**Issue by matthiasblum** [ProteinsWebTeam/interpro7-client#502]
If a protein does not have entry matches (InterPro or member database signatures), the protein summary page never fully loads. The _Family membership_ field keeps loading and the protein viewer never shows.

Examples:

* no entry matches, but sequence features: http://www.ebi.ac.uk/interpro/protein/UniProt/Q9WIJ4/
* no matches nor sequence features: http://www.ebi.ac.uk/interpro/protein/UniProt/A0A0A9M4N2/

**Comment by gustavo-salazar** [comment]
A hot fix was deployed
