### ISSUE TITLE
Missing numbers in TotalNb component

### ISSUE THREAD

**Issue by matthiasblum** [ProteinsWebTeam/interpro7-client#507]
The number of records in the table (e.g. `1 - 3 of 3...`) is missing, as reported in #506.

Example:

![image](https://github.com/ProteinsWebTeam/interpro7-client/assets/2097501/082ae324-c405-4f20-a559-f306114dfe6b)

**Comment by gustavo-salazar** [comment]
This was a problem with the new version of shifty the animation library we are using. The fix is now in `dev`: 3dc7d6555df0678339e24175940ebb1ab5031411
