### ISSUE TITLE
Download tool format error

### ISSUE THREAD

**Issue by aurel-l** [ProteinsWebTeam/interpro7-client#51]
The generate file tool has an issue with JSON and ND-JSON format file generation.
Both of them generate a list of accessions instead of the correct format.
Since this is the format by default inside the worker it might be because the wanted format is either not correctly passed inside the download worker (missing argument somewhere?) or not read properly (casing?). Fasta works fine.

Example: [https://www.ebi.ac.uk/interpro/beta/result/download/#/protein/UniProt/entry/InterPro/IPR000001/taxonomy/uniprot/10020/|ndjson](https://www.ebi.ac.uk/interpro/beta/result/download/#/protein/UniProt/entry/InterPro/IPR000001/taxonomy/uniprot/10020/|ndjson)

**Comment by CodeGit** [comment]
Fixed the bug. Removed nd-json option as we should keep things simple. Included instructions for users to enable nd-json in comments.
