### ISSUE TITLE
Set a maximum size to tooltips

### ISSUE THREAD

**Issue by matthiasblum** [ProteinsWebTeam/interpro7-client#518]
Most tooltips are sized automatically based on their content, which leads to over-wide tooltips.

Examples: https://www.ebi.ac.uk/interpro/entry/InterPro/IPR000001/

- Overlapping homologous superfamilies
- Add your annotations
- EC (cross references section)

**Comment by typhainepl** [comment]
Another example: https://www.ebi.ac.uk/interpro/entry/pirsf/PIRSF500625/
