### ISSUE TITLE
Fix Label Content button on Set pages

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#524]
The button isn't aligned properly and overlaps the left-hand side menu. The width of the drop-down is too small, making the content unaligned.
e.g. https://www.ebi.ac.uk/interpro/set/pirsf/PIRSF000047/#table

**Comment by gustavo-salazar** [comment]
I think this was fixed in a03b907 when migrating the summary to TS.
This hasn't been deployed in live but is available in dev: http://wp-np3-bd/interpro/set/pfam/CL0001/#table

I'll close this once it is merge to `master`
