### ISSUE TITLE
Add a page with Pfam training materials to the InterPro website

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#532]
The list of Pfam training materials is available in the [Pfam documentation](https://pfam-docs.readthedocs.io/en/latest/training.html). 
It would be great to create a page for the Pfam training materials in a similar way that we do for InterPro materials.

**Comment by gustavo-salazar** [comment]
The link was included a couple of releases ago: https://www.ebi.ac.uk/interpro/help/documentation/
