### ISSUE TITLE
Protvista show Empty "Predictions" track

### ISSUE THREAD

**Issue by sebpca** [ProteinsWebTeam/interpro7-client#56]
To remove the track by default if nothing there?
https://www.ebi.ac.uk/interpro/beta/protein/reviewed/A0A023GPI8/structure/PDB/#table
![image](https://user-images.githubusercontent.com/11173535/49306298-beb5f600-f4c9-11e8-9f97-6307fb79beee.png)
Also, the order of the tracks (for domains, family, site etc)  is different from the overview (should structure be on top?)

**Comment by 4ndr01d3** [comment]
Now the ProtVista component filters out the empty categories.
In `dev` branch
