### ISSUE TITLE
restructure Help & documentation

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#563]
Is an extra item in the menu and an extra page _really_ what we need?

We already have the _Help_ and _About_ buttons, each with their own submenu. That's twelve pages. Some contain links to ReadTheDocs. Some actually _import_ their content from ReadTheDocs.

We have a link to the support & feedback form:

* in the [FAQ](https://www.ebi.ac.uk/interpro/help/faqs/) (imported from ReadTheDocs)
* on the [Training page](https://www.ebi.ac.uk/interpro/help/training/) (imported from ReadTheDocs)
* on the [Documentation page](https://www.ebi.ac.uk/interpro/help/documentation/)
* and now on the new Contact Us page

Also, the Help/About section are kind of overlapping/interconnecting (the content between `Help >FAQ` and `About > InterPro` is quite redundant).

Maybe we could simplify this part of the website, e.g. one "Help center" page, that contains:

- links to training material (tutorial, webinars, future courses)
- links to various documentations (InterPro, Pfam, InterProScan)
- links to InterPro/Pfam support & feedback forms, and social medias

_Originally posted by @matthiasblum in https://github.com/ProteinsWebTeam/interpro7-client/issues/558#issuecomment-1879340911_

**Comment by matthiasblum** [comment]
Done in #663
