### ISSUE TITLE
Browse table - selecting an item on the member database filter should clear all other filters

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#57]
Select InterPro then entry type families. Then navigate to CDD - whoops error screen :)

The best solution would probably be to treat the member database as a major selection which causes all other filters to be reset.

![screenshot 2018-12-03 at 14 32 50](https://user-images.githubusercontent.com/892047/49379980-75071e80-f708-11e8-918b-632f4887fa70.png)
![screenshot 2018-12-03 at 14 33 00](https://user-images.githubusercontent.com/892047/49379987-7a646900-f708-11e8-8d9d-5541dd082c97.png)

**Comment by 4ndr01d3** [comment]
Fix is now in dev branch
