### ISSUE TITLE
structure page "tag"

### ISSUE THREAD

**Issue by blazaropinto** [ProteinsWebTeam/interpro7-client#600]
In the structure page, 'pdb' is lowercase in "pdb structure" in the current release, but it used to be uppercase ("PDB stucture"). 
example: https://www.ebi.ac.uk/interpro/structure/PDB/1t2v/

**Comment by gustavo-salazar** [comment]
I'm busy checking why this happens, but I actually think it is a side effect of something else.

@matthiasblum The [API root response](https://www.ebi.ac.uk/interpro/api/) with the information for databases doesn't include PDB, but I'm pretty sure it was there on previous releases. Has anything change? I could manually added to the DB, but I guess rather check that it gets included in the release procedures

**Comment by matthiasblum** [comment]
Correct. PDB and ENZYME were ignored in the two previous releases. They will be propagated again for the next release (101.0).

**Comment by gustavo-salazar** [comment]
The correct format of the name is now provided by the API and then displayed accordingly in PDB pages.
