### ISSUE TITLE
Some tracks keep expanding horizontally

### ISSUE THREAD

**Issue by matthiasblum** [ProteinsWebTeam/interpro7-client#637]
Does not affect all pages.

Example: [PDB structures matching Pfam entry PF11133](https://www.ebi.ac.uk/interpro/entry/pfam/PF11133/structure/PDB/#table)

Maybe related to #580 but for width instead of height?

**Comment by apolignano** [comment]
Closed by #649

**Comment by apolignano** [comment]
Closed by #649
