### ISSUE TITLE
Add filter for AI-generated entries in Browse

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#644]
It would be nice to be able to filter the list of InterPro entries and member DB signatures by AI-generated/Manually created in the Browse.

**Comment by matthiasblum** [comment]
Curation status filter added on the left of the table of InterPro entries and member database signatures, e.g. [InterPro](https://www.ebi.ac.uk/interpro/entry/InterPro/#table), [PANTHER](https://www.ebi.ac.uk/interpro/entry/panther/#table).

**Comment by typhainepl** [comment]
I've noticed, that's great, thank you for adding it.
