### ISSUE TITLE
Taxonomy tree viewer & Structure viewer navigation and scrolling happening at same time

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#66]
Navigating the tree with the cursor keys is difficult when the down/up keys trigger a page scroll as well as the selection of a different note

[https://www.ebi.ac.uk/interpro/beta/taxonomy/uniprot/68297/](url)
![Screenshot 2019-05-14 at 09 29 44](https://user-images.githubusercontent.com/892047/57683059-e12c6d80-762a-11e9-9a7c-1a2e1a231d02.png)

**Comment by gustavo-salazar** [comment]
I couldn't replicate the error on the taxonomy tree, but for the structure viewer it is either a configuration in NGL, or something they themselves need to change, I open an issue in their github:
https://github.com/arose/ngl/issues/662

**Comment by gustavo-salazar** [comment]
Issue fixed by updating NGL. See https://github.com/arose/ngl/issues/662 for details
