### ISSUE TITLE
3D viewer controls ie rotate, animate, splitscreen disappear in split screen & full screen view

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#67]
![Screenshot 2019-05-14 at 13 37 05](https://user-images.githubusercontent.com/892047/57698361-632d8e00-764d-11e9-81ff-722540e0b927.png)

**Comment by gustavo-salazar** [comment]
Fixed and deployed. Example: https://www.ebi.ac.uk/interpro/beta/structure/PDB/101m/#table
