### ISSUE TITLE
Add Outreach section in Help

### ISSUE THREAD

**Issue by typhainepl** [ProteinsWebTeam/interpro7-client#675]
There used to be a page about the Protein families game on the website, which is now missing.
Can you please add a new section 'Outreach' to the Help tab of the website that points to https://www.ebi.ac.uk/interpro/help/protein_families_game/

**Comment by typhainepl** [comment]
Adding it to the current training card sounds sensible to me.
_Training & public engagement_ or _Training & Outreach_, which ever fits best.

**Comment by matthiasblum** [comment]
@typhainepl the parser/formatter doesn't seem to handle email addresses, and produces an incorrect link.

Your email address is used in the _Translation_ section:

```rst
We are looking for volunteers to help us translate the game in different languages to increase its accessibility.
Please `contact us <typhaine@ebi.ac.uk>`_ if this is something you'd like to do.
```

Possible solutions:

1. Replace your email address to a link to the helpdesk form
2. Keep your email address, but in plain text
3. Users visiting https://www.ebi.ac.uk/interpro/help/protein_families_game/ are redirected to the corresponding page on ReadTheDocs

Let me know what you prefer.

**Comment by typhainepl** [comment]
Good catch, I've updated the documentation to point to the helpdesk form.
