### ISSUE TITLE
Misleading error?

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-client#69]
'Valid query, but unfortunately no data was available on the server' - from trying to look for repeats in a non-repeat db. maybe the error needs tweaking, or the invalid options greying out. the text is a bit clunky - isn't clear why there are no hits.

**Comment by potter-s** [comment]
BTW - the "Valid query, but unfortunately no data was available on the server" error happens in several places. I had it also when putting in the partial text of a non-existent species name. It might be a lot of work (and not urgent) but I think these errors might benefit from a bit of customisation. e.g. 'there is no species which matches "XYZ"'.

**Comment by gustavo-salazar** [comment]
Some improvements Included in Tag [1.2.0](https://github.com/ProteinsWebTeam/interpro7-client/tree/1.2.0)
