### ISSUE TITLE
protein size?

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-client#70]
What's protein size? (tooltip?) https://www.ebi.ac.uk/interpro/beta/protein/reviewed/entry/profile/taxonomy/uniprot/10090/?size=medium#table should they be in the list in order small->med->large?

**Comment by happy-lorna** [comment]
Agreed this is a weird arbitrary separation. It would make sense to separate into fragment/non-fragment (as specified by UniProt) instead.

**Comment by gustavo-salazar** [comment]
The original filter allowed the user to filter for any arbitrary length. this however proof to be a bit too much for our data store. And that's where the size category comes from.
Maybe adding some text (tooltip?) telling what we call small, medium or large?

**Comment by matthiasblum** [comment]
Also, we have three sizes at the moment:
1. small (up to 100 AA)
2. medium (from 101 to 1000 AAA)
3. large (more than 1000 AA). 

But the vast majority (85%) of proteins are in the 101-1000 AA range. We could add one or two intermediate sizes.

**Comment by happy-lorna** [comment]
I can't think of a use-case where this would be useful. Fragment vs non-fragment would be more useful.

**Comment by gustavo-salazar** [comment]
@rdfinn @almitchell We thinking of adding a filter for Fragment vs non-fragment. but should we remove the size filter, or should we have both?

**Comment by almitchell** [comment]
I would vote for keeping both - they are filtering on different aspects of the data.

**Comment by almitchell** [comment]
Hmm, actually, having checked, I am not sure having the 'small, medium, large' proteins classification is useful (I thought there was a slider for protein size, but now I remember the overhead for that was too great). If it is a choice between 'small, medium, large' and 'fragments' or both options, I would just keep the 'fragments' option.

**Comment by matthiasblum** [comment]
@gustavo-salazar the dev/test Elasticsearch documents have now a `protein_is_fragment` field.
