### ISSUE TITLE
i5 search - error when going back to previous page in browser

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-client#71]
To replicate: from a completed i5 search, go to 'Sequence' and choose 'search selection with interproscan' (without selecting anything) and then from the new page just hit browser back. I get an error (Firefox) 'An error happened while trying to load a component of this page.'

**Comment by gustavo-salazar** [comment]
I manage to replicate in chrome. I will investigate.

**Comment by gustavo-salazar** [comment]
Fixed and deployed in dev: http://wp-np3-ab.ebi.ac.uk/interpro7/result/InterProScan/#table
