### ISSUE TITLE
aa colour key in protein view page

### ISSUE THREAD

**Issue by happy-lorna** [ProteinsWebTeam/interpro7-client#72]
Need to include some information somewhere about what the colours (blue/yellow range) indicate for the aa sequence in the protein view page.

**Comment by gustavo-salazar** [comment]
I was thinking of adding a graphic scale on the tooltip. 
-2 |=====| 2

**Comment by gustavo-salazar** [comment]
Fixed and deployed in dev: http://wp-np3-ab.ebi.ac.uk/interpro7/protein/UniProt/A0A000/#table
