### ISSUE TITLE
Missing hierarchy information on InterPro pages

### ISSUE THREAD

**Issue by happy-lorna** [ProteinsWebTeam/interpro7-client#74]
InterPro relationships (hierarchy) is not being shown on the InterPro entry pages.
e.g. https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR003524/

**Comment by gustavo-salazar** [comment]
Fixed. for now deployed in dev: http://wp-np3-ab.ebi.ac.uk/interpro7/entry/InterPro/IPR000003/
