### ISSUE TITLE
Export FASTA - taxonomy filtering missing

### ISSUE THREAD

**Issue by mifraser** [ProteinsWebTeam/interpro7-client#76]
From http://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR042311/protein/UniProt/taxonomy/uniprot/11099/#table click "Export FASTA". It says we should expect 426 proteins but the export file contains 1575 (it's not including the taxonomy in the filtering).

The same applies to Proteomes and maybe more.

**Comment by gustavo-salazar** [comment]
Fixed and deployed in dev: http://wp-np3-ab.ebi.ac.uk/interpro7/entry/InterPro/IPR042311/protein/UniProt/taxonomy/uniprot/11099/#table
