### ISSUE TITLE
ProDom occurrences to review

### ISSUE THREAD

**Issue by mifraser** [ProteinsWebTeam/interpro7-client#77]
Remove the "ProDom" option from http://www.ebi.ac.uk/interpro/beta/search/sequence/ and any other relevant pages. E.g. it's also in http://www.ebi.ac.uk/interpro/beta/ and maybe more?

**Comment by gustavo-salazar** [comment]
Fixed and now available in the dev machine: http://wp-np3-ab.ebi.ac.uk/interpro7/

**Comment by matthiasblum** [comment]
Still in the sequence search (advanced options).

**Comment by gustavo-salazar** [comment]
Fix deployed in the dev machine: http://wp-np3-ab.ebi.ac.uk/interpro7/search/sequence/
