### ISSUE TITLE
Download page - InterProScan version not up-to-date

### ISSUE THREAD

**Issue by mifraser** [ProteinsWebTeam/interpro7-client#79]
InterProScan version on http://www.ebi.ac.uk/interpro/beta/download/ is not up-to-date

**Comment by gustavo-salazar** [comment]
Fixed and deployed on dev: http://wp-np3-ab.ebi.ac.uk/interpro7/download/

**Comment by gustavo-salazar** [comment]
We taking this version from github API, however, there is a limit of 60 connections per hour, we need to see if this becomes a problem
