### ISSUE TITLE
Use the formatted name for the member DBs in the member DB selector Text 

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#81]
In any page that has a member DB selector, and it shows on top of the table view, the text includes the canonical text, instead of the formatted one. as in this pic:
![pfam](https://user-images.githubusercontent.com/46671268/58036350-cd996f00-7b22-11e9-86a3-c7bd983b7517.png)

reported by @potter-s

**Comment by potter-s** [comment]
On this page, still seems to be "pfam": https://www.ebi.ac.uk/interpro/beta/entry/pfam/#table

**Comment by gustavo-salazar** [comment]
The change only got released today in to the live machines. it should be OK now.

**Comment by potter-s** [comment]
In the mouseover links (DB column) on e.g. https://www.ebi.ac.uk/interpro/beta/entry/pfam/#table these are also showing as lower case.

**Comment by gustavo-salazar** [comment]
Fix deployed in the dev machine: http://wp-np3-ab.ebi.ac.uk/interpro7/entry/pfam/#table
