### ISSUE TITLE
Update IUPHAR RECEPTOR CODE Links

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#83]
From: http://www.iuphar-db.org/GPCR/ReceptorDisplayForward?receptorID=2361
To: http://www.guidetopharmacology.org/GRAC/ObjectDisplayForward?objectId=288

Example: https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR000025/
Reported by @almitchell

**Comment by gustavo-salazar** [comment]
Unfortunately not as easy as changing the link:
Our links are using the receptorID, for example, we link to
http://www.iuphar-db.org/GPCR/ReceptorDisplayForward?receptorID=2361 and that server redirects to http://www.iuphar-db.org/DATABASE/ObjectDisplayForward?objectId=288 which in turn redirects to http://www.guidetopharmacology.org/GRAC/ObjectDisplayForward?objectId=288. 
But we don’t have a mapping between receptorID and objectID, so we can’t use that link directly.

I have mailed the contact email on guidetopharmacology to see if is there an alternative link to use

**Comment by gustavo-salazar** [comment]
I got a reply from guidetopharmacology, and they have provided a mapping file between the IDs. @matthiasblum suggest to use the file to update the IDs at production level. 
This then requires changing the links in:
* InterPro6 (@mifraser )
* InterPro7 (@gustavo-salazar )
* Pronto (@matthiasblum )
Could you guys let me know if we can do this as part of this sprint or do we need to create a story for the next one?

**Comment by gustavo-salazar** [comment]
In InterPro7 the change is on a config file, so it won't take long and then can be included in the following deploy of the app. It only requires the right IDs in the DW

**Comment by matthiasblum** [comment]
The production database has been updated with the new IDs from [Guide to PHARMACOLOGY](https://www.guidetopharmacology.org). 

- InterPro7: I'll refresh the DW during this weekend (I needed to to it anyway to fix #85 and include alternative isoforms).
- Pronto: turns out old cross-references are not displayed... so nothing to do.

**Comment by matthiasblum** [comment]
Test/dev DW refreshed. The new IDs are now used, e.g. [IPR000025](http://wp-np3-ab.ebi.ac.uk/interpro7/entry/InterPro/IPR000025/).

**Comment by gustavo-salazar** [comment]
The links have been updated in InterPro7 and for now in the dev machine. eg. [IPR000025](http://wp-np3-ab.ebi.ac.uk/interpro7/entry/InterPro/IPR000025/)
