### ISSUE TITLE
Remove COME links

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#84]
The COME links in the cross reference section are broken. e.g.https://www.ebi.ac.uk/interpro/beta/entry/InterPro/IPR001760/
The website (http://www.flymine.org/come/) hasn't been updated since 2005, and all its links are failing.

Needs to be remove from website, and maybe from DW (@matthiasblum)

Reported by @almitchell

**Comment by matthiasblum** [comment]
Cross-references to COMe have been deleted in the production database, which will be propagated to the DW during the next release.

**Comment by gustavo-salazar** [comment]
Example in dev: http://wp-np3-ab.ebi.ac.uk/interpro7/entry/InterPro/IPR001760/
