### ISSUE TITLE
Problems with the length of the Set alignments 

### ISSUE THREAD

**Issue by gustavo-salazar** [ProteinsWebTeam/interpro7-client#85]
Some alignments are been chunk, e.g. The page below cuts the alignment at 160, while there are families beyond that.

https://www.ebi.ac.uk/interpro/beta/set/cdd/cl00057/alignments/#table

**Comment by gustavo-salazar** [comment]
There is a data problem there. If you see the API response for the example: https://www.ebi.ac.uk/interpro/beta/api/set/cdd/cl00057/?alignments

The length of the alignment is 161 but there are domains that go beyond that:
```
 {
            "accession": "cd00198",
            "alignments_count": 23,
            "alignedTo": {
                "cd01450": {
                    "set_acc": "cl00057",
                    "score": 1.19e-17,
                    "length": 161,
                    "domains": [
                        {
                            "start": 2,
                            "end": 162
                        }
                    ]
                },
                "cd01465": {
                    "set_acc": "cl00057",
                    "score": 1.78e-14,
                    "length": 161,
                    "domains": [
                        {
                            "start": 2,
                            "end": 171
                        }
                    ]
                },
```
@matthiasblum Can you have a look to it?

**Comment by matthiasblum** [comment]
It looks this issue concerns only CDD sets, which is the only member database not using HMMER but COMPASS. I'll have to update sets later this sprint anyway as we are going to update CDD: I'll investigate then.

**Comment by matthiasblum** [comment]
Fixed in the dev/test DW, e.g. [cl00057 alignments](http://wp-np3-ab.ebi.ac.uk/interpro7/set/cdd/cl00057/alignments/#table).
