### ISSUE TITLE
Wrong handling of multiple sequences in InterProScan search

### ISSUE THREAD

**Issue by aurel-l** [ProteinsWebTeam/interpro7-client#88]
When sending multiple sequences through the InterProScan it accepts them, but then sends the whole string as one single job.
But InterProScan API doesn't support it.

example
`
>example protein sequence
MITIDGNGAV ASVAFRTSEV IAIYPITPSST MAEQADAWAGN GLKNVWGDTP RVVEMQSEAG
>example protein sequence
MITIDGNGAV ASVAFRTSEV IAIYPITPSST MAEQADAWAGN GLKNVWGDTP RVVEMQSEAG
>example protein sequence
MITIDGNGAV ASVAFRTSEV IAIYPITPSST MAEQADAWAGN GLKNVWGDTP RVVEMQSEAG
`

Maybe the component shouldn't accept it? The editor should display it as invalid?

Also, then on the result list page and the result overview page, it should handle better 404 from the server. Because right now it just says "created" forever, when it should display some kind of error status.

**Comment by gustavo-salazar** [comment]
Hey,
So I finally manage to put some time on this, for now only in the `dev` branch. 
I got the highlighting of the error and the button only gets activated if there is up to one header and it is at the top of the text.
For the auto correction button I'm removing any other header, so it combines the sequences. Not sure that's the best approach tho, what do you think?

**Comment by aurel-l** [comment]
Not really, I think it should strip anything below, and including, any header that follows a sequence

**Comment by gustavo-salazar** [comment]
Yep, that makes sense. 
I'll implement the change and probably by the end of the week will be released.
