### ISSUE TITLE
Enable filtering of entries by taxonomy IDs that are not species (ie. non terminal TaxIDs)

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#94]
Entries in InterPro 6 can be filtered by any taxid (e.g Primates or Metazoa) but entries in InterPro 7 can only be filtered by TaxIDs corresponding to species.

![Screenshot 2019-06-24 at 15 17 29](https://user-images.githubusercontent.com/892047/60026320-3ed4c080-9693-11e9-8080-d21a4402748a.png)

![Screenshot 2019-06-24 at 15 21 19](https://user-images.githubusercontent.com/892047/60026600-be628f80-9693-11e9-969c-b4a24b81dad5.png)

**Comment by gustavo-salazar** [comment]
Changes on PR #105

**Comment by gustavo-salazar** [comment]
Done and deployed. eg: https://www.ebi.ac.uk/interpro/beta/taxonomy/uniprot/entry/InterPro/?search=2#table
