### ISSUE TITLE
Add licence page to InterPro

### ISSUE THREAD

**Issue by CodeGit** [ProteinsWebTeam/interpro7-client#96]
e.g https://www.ebi.ac.uk/gxa/licence.html

**Comment by gustavo-salazar** [comment]
The interproscan page now includes the link to the apache licence, is that enough to close this ticket?

**Comment by gustavo-salazar** [comment]
Closing this, as it seems it was related to the interpro scan, and that is live here: https://www.ebi.ac.uk/interpro/about/interproscan/
