### ISSUE TITLE
i5 search - remove GO option?

### ISSUE THREAD

**Issue by potter-s** [ProteinsWebTeam/interpro7-client#99]
If the GO terms are calculated anyway, remove the option? Unchecking seemed to have no effect.

**Comment by gustavo-salazar** [comment]
Yeah, just give that a try, also not sure about the pathways option at the side.
@gsn7 do you know if those options are working on InterProScan?

**Comment by gustavo-salazar** [comment]
Options removed. See https://www.ebi.ac.uk/interpro/beta/search/sequence/
